package com.linCu.model.vvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 23 00:17:35 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CardApplicationVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CardApplicationVVOImpl() {
    }

    /**
     * Returns the variable value for bindCardType.
     * @return variable value for bindCardType
     */
    public String getbindCardType() {
        return (String) ensureVariableManager().getVariableValue("bindCardType");
    }

    /**
     * Sets <code>value</code> for variable bindCardType.
     * @param value value to bind as bindCardType
     */
    public void setbindCardType(String value) {
        ensureVariableManager().setVariableValue("bindCardType", value);
    }

    /**
     * Returns the variable value for bindMemberId.
     * @return variable value for bindMemberId
     */
    public String getbindMemberId() {
        return (String) ensureVariableManager().getVariableValue("bindMemberId");
    }

    /**
     * Sets <code>value</code> for variable bindMemberId.
     * @param value value to bind as bindMemberId
     */
    public void setbindMemberId(String value) {
        ensureVariableManager().setVariableValue("bindMemberId", value);
    }
}

