package com.linCu.model.vvo;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 03 21:56:40 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LincuUnionsVVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CreditUnionId,
        CreditUnionCode,
        CreditUnionName;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CREDITUNIONID = AttributesEnum.CreditUnionId.index();
    public static final int CREDITUNIONCODE = AttributesEnum.CreditUnionCode.index();
    public static final int CREDITUNIONNAME = AttributesEnum.CreditUnionName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LincuUnionsVVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute CreditUnionId.
     * @return the CreditUnionId
     */
    public String getCreditUnionId() {
        return (String) getAttributeInternal(CREDITUNIONID);
    }

    /**
     * Gets the attribute value for the calculated attribute CreditUnionCode.
     * @return the CreditUnionCode
     */
    public String getCreditUnionCode() {
        return (String) getAttributeInternal(CREDITUNIONCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute CreditUnionName.
     * @return the CreditUnionName
     */
    public String getCreditUnionName() {
        return (String) getAttributeInternal(CREDITUNIONNAME);
    }
}

