package com.linCu.model.vvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Mar 11 00:27:03 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LoginVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LoginVVOImpl() {
    }

    /**
     * Returns the variable value for bindUserName.
     * @return variable value for bindUserName
     */
    public String getbindUserName() {
        return (String) ensureVariableManager().getVariableValue("bindUserName");
    }

    /**
     * Sets <code>value</code> for variable bindUserName.
     * @param value value to bind as bindUserName
     */
    public void setbindUserName(String value) {
        ensureVariableManager().setVariableValue("bindUserName", value);
    }
}

