package com.linCu.model.vvo;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 04 01:07:17 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LookUpDataVVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        LookupId,
        LookupType,
        LookupCode,
        LookupDesc;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int LOOKUPID = AttributesEnum.LookupId.index();
    public static final int LOOKUPTYPE = AttributesEnum.LookupType.index();
    public static final int LOOKUPCODE = AttributesEnum.LookupCode.index();
    public static final int LOOKUPDESC = AttributesEnum.LookupDesc.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LookUpDataVVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute LookupId.
     * @return the LookupId
     */
    public BigDecimal getLookupId() {
        return (BigDecimal) getAttributeInternal(LOOKUPID);
    }

    /**
     * Gets the attribute value for the calculated attribute LookupType.
     * @return the LookupType
     */
    public String getLookupType() {
        return (String) getAttributeInternal(LOOKUPTYPE);
    }

    /**
     * Gets the attribute value for the calculated attribute LookupCode.
     * @return the LookupCode
     */
    public String getLookupCode() {
        return (String) getAttributeInternal(LOOKUPCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute LookupDesc.
     * @return the LookupDesc
     */
    public String getLookupDesc() {
        return (String) getAttributeInternal(LOOKUPDESC);
    }
}

