package com.linCu.model.vvo;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 04 01:21:35 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OccupationCodesVVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        OccupationId,
        OccupationDes;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int OCCUPATIONID = AttributesEnum.OccupationId.index();
    public static final int OCCUPATIONDES = AttributesEnum.OccupationDes.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OccupationCodesVVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute OccupationId.
     * @return the OccupationId
     */
    public String getOccupationId() {
        return (String) getAttributeInternal(OCCUPATIONID);
    }

    /**
     * Gets the attribute value for the calculated attribute OccupationDes.
     * @return the OccupationDes
     */
    public String getOccupationDes() {
        return (String) getAttributeInternal(OCCUPATIONDES);
    }
}

