package com.linCu.model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 14 16:25:33 IST 2017
// ---------------------------------------------------------------------
public interface CreditUnionVO extends ViewObject {
    void createCreditUnion(String user);

    void updateCreditUnion(String user);
}

