package com.linCu.model.view.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 27 16:41:34 IST 2017
// ---------------------------------------------------------------------
public interface CreditUnionVORow extends Row {
    void closeCreditUnion();
}

