package com.linCu.model.view.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 28 13:29:18 IST 2017
// ---------------------------------------------------------------------
public interface CreditUnionBranchVORow extends Row {
    void closeBranch();
}

