package com.linCu.model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 14 18:02:13 IST 2017
// ---------------------------------------------------------------------
public interface CreditUnionBranchVO extends ViewObject {
    void createBranch(String user);

    void updateBranch(String user);
}

