package com.linCu.model.view.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 27 19:33:10 IST 2017
// ---------------------------------------------------------------------
public interface LincuMemberVORow extends Row {
    void closeMember();

    void approveMember(String user);

    void rejectMember(String user);
}

