package com.linCu.model.view.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 25 00:22:44 IST 2017
// ---------------------------------------------------------------------
public interface LincuMemberCardVORow extends Row {
    void closeCard();
}

