package com.linCu.model.view.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 27 18:30:00 IST 2017
// ---------------------------------------------------------------------
public interface LincuUserInfoVORow extends Row {
    void closeUser();
}

