package com.linCu.model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 10 07:57:02 IST 2017
// ---------------------------------------------------------------------
public interface LincuMemberCardDocsVO extends ViewObject {
    void removeCurrentRow();
}

