CREATE TABLE COUNTRY_CODES 
(
  COUNTRY_ID VARCHAR2(20 BYTE) NOT NULL 
, COUNTRY_NAME VARCHAR2(100 BYTE) NOT NULL 
, CONSTRAINT COUNTRY_CODES_PK PRIMARY KEY 
  (
    COUNTRY_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX COUNTRY_CODES_PK ON COUNTRY_CODES (COUNTRY_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE COUNTRY_CODES
ADD CONSTRAINT COUNTRY_CODES_UK1 UNIQUE 
(
  COUNTRY_NAME 
)
USING INDEX 
(
    CREATE UNIQUE INDEX COUNTRY_CODES_UK1 ON COUNTRY_CODES (COUNTRY_NAME ASC) 
    LOGGING 
    TABLESPACE LINCU 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 65536 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      PCTINCREASE 0 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;

Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('1','TRINIDAD & TOBAGO');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('14','GRENADA, ST. VINCENT AND ST. LUCIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('19','OTHER CARIFTA COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('33','BAHAMAS AND CAYMAN ISLANDS');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('39','OTHER COMMONWEALTH');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('49','OTHER COUNTRIES');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('99','NO DECLARATION OF RESIDENCE');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('100','AFGHANISTAN');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('101','ALBANIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('102','ALGERIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('103','ANGOLA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('104','ANGUILLA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('105','ANTIGUA-BARBUDA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('106','ARGENTINA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('107','ARUBA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('108','ASCENSION');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('109','AUSTRALIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('110','AUSTRIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('111','BAHAMAS');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('112','BAHRAIN');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('113','BANGLADESH');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('114','BARBADOS');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('117','BERMUDA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('118','BOLIVIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('119','BOSNIA AND HERZEGOVINA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('120','BOTSWANA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('123','BULGARIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('124','BURKINA FASO');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('125','BURUNDI');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('126','CAMEROON');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('127','CANADA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('128','CARICOM');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('129','CAYMAN ISLANDS');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('130','CHAD');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('131','CHILE');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('132','CHINA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('133','COLOMBIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('134','CONGO');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('135','CONGO,THE DEMOCRATIC REPUBLIC');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('136','COSTA RICA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('137','CÔTE D''IVOIRE');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('138','CROATIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('139','CUBA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('140','CYPRUS');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('141','CZECH REPUBLIC');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('142','DENMARK');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('143','DOMINICA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('144','DOMINICAN REPUBLIC');

CREATE TABLE LINCU_ROLES 
(
  ROLE_ID NUMBER NOT NULL 
, ROLE VARCHAR2(20 BYTE) NOT NULL 
, ROLE_DESCRIPTION VARCHAR2(100 BYTE) NOT NULL 
, CONSTRAINT LINCU_ROLES_PK PRIMARY KEY 
  (
    ROLE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LINCU_USER_ROLES_PK ON LINCU_ROLES (ROLE_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE LINCU_ROLES
ADD CONSTRAINT LINCU_ROLES_UK1 UNIQUE 
(
  ROLE 
)
USING INDEX 
(
    CREATE UNIQUE INDEX LINCU_USER_ROLES_UK1 ON LINCU_ROLES (ROLE ASC) 
    LOGGING 
    TABLESPACE LINCU 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 65536 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      PCTINCREASE 0 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;

Insert into LINCU_ROLES (ROLE_ID,ROLE,ROLE_DESCRIPTION) values (1,'MSR','Member Service Representative');
Insert into LINCU_ROLES (ROLE_ID,ROLE,ROLE_DESCRIPTION) values (2,'SUP','Supervisor / Authorizer');
Insert into LINCU_ROLES (ROLE_ID,ROLE,ROLE_DESCRIPTION) values (3,'MAN_ADMIN','Administrator');
Insert into LINCU_ROLES (ROLE_ID,ROLE,ROLE_DESCRIPTION) values (4,'PREPAID_ADMIN','Prepaid Card System System Administrator');
Insert into LINCU_ROLES (ROLE_ID,ROLE,ROLE_DESCRIPTION) values (5,'FCB','FCB User');

CREATE TABLE CREDIT_UNION 
(
  CREDIT_UNION_ID VARCHAR2(10 BYTE) NOT NULL 
, CREDIT_UNION_CODE VARCHAR2(2 BYTE) NOT NULL 
, CREDIT_UNION_NAME VARCHAR2(100 BYTE) NOT NULL 
, CREDIT_UNION_ADDRES_1 VARCHAR2(100 BYTE) NOT NULL 
, CREDIT_UNION_ADDRES_2 VARCHAR2(100 BYTE) 
, CREDIT_UNION_ADDRES_3 VARCHAR2(100 BYTE) 
, CREDIT_UNION_ADDRES_4 VARCHAR2(100 BYTE) 
, CREDIT_UNION_CITY VARCHAR2(100 BYTE) NOT NULL 
, CREDIT_UNION_COUNTRY VARCHAR2(100 BYTE) NOT NULL 
, CREDIT_UNION_PHONE_1 VARCHAR2(15 BYTE) NOT NULL 
, CREDIT_UNION_PHONE_2 VARCHAR2(15 BYTE) 
, CREDIT_UNION_FAX VARCHAR2(15 BYTE) 
, CREDIT_UNION_EMAIL_ID VARCHAR2(50 BYTE) NOT NULL 
, CREATED_BY VARCHAR2(60 BYTE) NOT NULL 
, CREATION_DATE DATE NOT NULL 
, LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL 
, LAST_UPDATE_DATE DATE NOT NULL 
, OBJECT_VERSION_ID NUMBER(15, 0) NOT NULL 
, LAST_APPROVED_BY VARCHAR2(60 BYTE) NOT NULL 
, LAST_APPROVED_DATE DATE NOT NULL 
, CONSTRAINT CREDIT_UNION_PK PRIMARY KEY 
  (
    CREDIT_UNION_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CREDIT_UNION_PK ON CREDIT_UNION (CREDIT_UNION_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE CREDIT_UNION_BRANCH 
(
  CREDIT_UNION_ID VARCHAR2(10 BYTE) NOT NULL 
, CREDIT_UNION_BRANCH_ID VARCHAR2(10 BYTE) NOT NULL 
, CREDIT_UNION_BRANCH_CODE VARCHAR2(2 BYTE) NOT NULL 
, CREDIT_UNION_BRANCH_NAME VARCHAR2(100 BYTE) NOT NULL 
, CREDIT_UNION_ADDRES_1 VARCHAR2(100 BYTE) NOT NULL 
, CREDIT_UNION_ADDRES_2 VARCHAR2(100 BYTE) 
, CREDIT_UNION_ADDRES_3 VARCHAR2(100 BYTE) 
, CREDIT_UNION_ADDRES_4 VARCHAR2(100 BYTE) 
, CREDIT_UNION_CITY VARCHAR2(100 BYTE) NOT NULL 
, CREDIT_UNION_COUNTRY VARCHAR2(100 BYTE) NOT NULL 
, CREDIT_UNION_PHONE_1 VARCHAR2(15 BYTE) NOT NULL 
, CREDIT_UNION_PHONE_2 VARCHAR2(15 BYTE) 
, CREDIT_UNION_EMAIL_ID VARCHAR2(50 BYTE) NOT NULL 
, CREATED_BY VARCHAR2(60 BYTE) NOT NULL 
, CREATION_DATE DATE NOT NULL 
, LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL 
, LAST_UPDATE_DATE DATE NOT NULL 
, OBJECT_VERSION_ID NUMBER(15, 0) NOT NULL 
, LAST_APPROVED_BY VARCHAR2(60 BYTE) NOT NULL 
, LAST_APPROVED_DATE DATE NOT NULL 
, CONSTRAINT CREDIT_UNION_BRANCH_PK PRIMARY KEY 
  (
    CREDIT_UNION_ID 
  , CREDIT_UNION_BRANCH_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CREDIT_UNION_BRANCH_PK ON CREDIT_UNION_BRANCH (CREDIT_UNION_ID ASC, CREDIT_UNION_BRANCH_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE CREDIT_UNION_BRANCH
ADD CONSTRAINT CREDIT_UNION_BRANCH_FK FOREIGN KEY
(
  CREDIT_UNION_ID 
)
REFERENCES CREDIT_UNION
(
  CREDIT_UNION_ID 
)
ENABLE;

CREATE TABLE LINCU_LOOKUPS 
(
  LOOKUP_ID NUMBER NOT NULL 
, LOOKUP_TYPE VARCHAR2(30 BYTE) 
, LOOKUP_CODE VARCHAR2(30 BYTE) 
, LOOKUP_DESC VARCHAR2(250 BYTE) 
, CONSTRAINT LINCU_LOOKUPS_PK PRIMARY KEY 
  (
    LOOKUP_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LINCU_LOOKUPS_PK ON LINCU_LOOKUPS (LOOKUP_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE LINCU_LOOKUPS
ADD CONSTRAINT LINCU_LOOKUPS_UK1 UNIQUE 
(
  LOOKUP_TYPE 
, LOOKUP_CODE 
)
USING INDEX 
(
    CREATE UNIQUE INDEX LINCU_LOOKUPS_UK1 ON LINCU_LOOKUPS (LOOKUP_TYPE ASC, LOOKUP_CODE ASC) 
    LOGGING 
    TABLESPACE LINCU 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 65536 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      PCTINCREASE 0 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;

 Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (1,'USER_TYPE_CODE','LINCU','LinCu');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (2,'USER_TYPE_CODE','FCB','FCB');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (3,'SECURITY_QUESTION','FIRST_PET','Name of first pet');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (4,'SECURITY_QUESTION','FAV_PET','Name of favorite pet');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (5,'SECURITY_QUESTION','MOTHER_MAIDEN','Mother’s maiden name');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (6,'SECURITY_QUESTION','STREET_LIVED','Name of street you lived on as a child');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (7,'SECURITY_QUESTION','BIRTH_CITY','City of birth');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (8,'SECURITY_QUESTION','FAV_MOVIE','Favorite movie');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (9,'SECURITY_QUESTION','FAV_BOOK','Favorite book');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (10,'SECURITY_QUESTION','FAV_SONG','Favorite song');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (11,'CARD_TYPE','NEW_CARD','New Card');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (12,'CARD_TYPE','ADDON_CARD','Addon Card');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (13,'CARD_TYPE','TOPUP_CARD','Topup Card');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (14,'APPLICATION_STATUS','DRAFT','Draft');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (15,'APPLICATION_STATUS','SUBMITTED','Submitted');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (16,'APPLICATION_STATUS','REJECTED','Rejected');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (17,'APPLICATION_STATUS','AUTHORIZED','Authorized');

CREATE TABLE LINCU_USER_INFO 
(
  USER_ID NUMBER(15, 0) NOT NULL 
, FIRST_NAME VARCHAR2(30 BYTE) 
, LAST_NAME VARCHAR2(30 BYTE) 
, CREDIT_UNION_ID VARCHAR2(10 BYTE) NOT NULL 
, CREDIT_UNION_BRANCH_ID VARCHAR2(10 BYTE) NOT NULL 
, USER_TYPE_CODE VARCHAR2(30 BYTE) NOT NULL 
, USER_ROLE VARCHAR2(30 BYTE) NOT NULL 
, USER_SUPERVISOR VARCHAR2(30 BYTE) 
, EMAIL VARCHAR2(25 BYTE) NOT NULL 
, MOBILE_PHONE_NUMBER VARCHAR2(20 BYTE) 
, DATE_OF_BIRTH DATE 
, GENDER VARCHAR2(1 BYTE) NOT NULL 
, CREATED_BY VARCHAR2(60 BYTE) NOT NULL 
, CREATION_DATE DATE NOT NULL 
, LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL 
, LAST_UPDATE_DATE DATE NOT NULL 
, OBJECT_VERSION_ID NUMBER(15, 0) NOT NULL 
, LAST_APPROVED_BY VARCHAR2(60 BYTE) NOT NULL 
, LAST_APPROVED_DATE DATE NOT NULL 
, PASSWORD VARCHAR2(30 BYTE) NOT NULL 
, USER_NAME VARCHAR2(50 BYTE) NOT NULL 
, SECURITY_QUSTN VARCHAR2(50 BYTE) 
, SECURITY_QUSTN_ANS VARCHAR2(250 BYTE) 
, FIRST_LOGIN_FLAG VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL 
, CONSTRAINT LINCU_USER_INFO_PK PRIMARY KEY 
  (
    USER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LINCU_USER_INFO_PK ON LINCU_USER_INFO (USER_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE LINCU_USER_INFO
ADD CONSTRAINT LINCU_USER_INFO_UK1 UNIQUE 
(
  USER_ID 
, CREDIT_UNION_ID 
, CREDIT_UNION_BRANCH_ID 
)
USING INDEX 
(
    CREATE UNIQUE INDEX LINCU_USER_INFO_UK1 ON LINCU_USER_INFO (USER_ID ASC, CREDIT_UNION_ID ASC, CREDIT_UNION_BRANCH_ID ASC) 
    LOGGING 
    TABLESPACE LINCU 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 65536 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      PCTINCREASE 0 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;

ALTER TABLE LINCU_USER_INFO
ADD CONSTRAINT LINCU_USER_INFO_FK_1 FOREIGN KEY
(
  CREDIT_UNION_ID 
, CREDIT_UNION_BRANCH_ID 
)
REFERENCES CREDIT_UNION_BRANCH
(
  CREDIT_UNION_ID 
, CREDIT_UNION_BRANCH_ID 
)
ENABLE;

ALTER TABLE LINCU_USER_INFO
ADD CONSTRAINT USER_GENDER_CHK CHECK 
(GENDER in ('M','F'))
ENABLE;


CREATE TABLE LINCU_MEMBER_INFO 
(
  MEMBER_ID VARCHAR2(15 BYTE) NOT NULL 
, CREDIT_UNION_ID VARCHAR2(10 BYTE) NOT NULL 
, CREDIT_UNION_BRANCH_ID VARCHAR2(10 BYTE) NOT NULL 
, MEMBER_PREFIX VARCHAR2(5 BYTE) NOT NULL 
, FIRST_NAME VARCHAR2(17 BYTE) NOT NULL 
, MIDDLE_NAME VARCHAR2(30 BYTE) 
, LAST_NAME VARCHAR2(30 BYTE) NOT NULL 
, DATE_OF_BIRTH DATE 
, GENDER VARCHAR2(1 BYTE) 
, EMAIL VARCHAR2(60 BYTE) 
, HOME_PHONE_NUMBER VARCHAR2(12 BYTE) 
, BUSINESS_PHONE_NUMBER VARCHAR2(12 BYTE) 
, BUSINESS_PHONE_EXTN VARCHAR2(4 BYTE) 
, MOBILE_PHONE_NUMBER VARCHAR2(12 BYTE) 
, FAX_NUMBER VARCHAR2(30 BYTE) 
, TIN_OR_SID VARCHAR2(20 BYTE) 
, CREATED_BY VARCHAR2(60 BYTE) NOT NULL 
, CREATION_DATE DATE NOT NULL 
, LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL 
, LAST_UPDATE_DATE DATE NOT NULL 
, OBJECT_VERSION_ID NUMBER(15, 0) NOT NULL 
, LAST_APPROVED_BY VARCHAR2(60 BYTE) NOT NULL 
, LAST_APPROVED_DATE DATE NOT NULL 
, CONSTRAINT LINCU_MEMBER_INFO_PK PRIMARY KEY 
  (
    MEMBER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LINCU_MEMBER_INFO_PK ON LINCU_MEMBER_INFO (MEMBER_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE LINCU_MEMBER_INFO
ADD CONSTRAINT LINCU_MEMBER_INFO_FK_1 FOREIGN KEY
(
  CREDIT_UNION_ID 
, CREDIT_UNION_BRANCH_ID 
)
REFERENCES CREDIT_UNION_BRANCH
(
  CREDIT_UNION_ID 
, CREDIT_UNION_BRANCH_ID 
)
ENABLE;

ALTER TABLE LINCU_MEMBER_INFO
ADD CONSTRAINT MEMBER_GENDER_CHK CHECK 
(GENDER in ('M','F'))
ENABLE;

CREATE TABLE LINCU_MEMBER_KYC 
(
  MEMBER_ID VARCHAR2(15 BYTE) NOT NULL 
, CREDIT_UNION_ID VARCHAR2(10 BYTE) NOT NULL 
, CREDIT_UNION_BRANCH_ID VARCHAR2(10 BYTE) NOT NULL 
, ELECTORIAL_ID VARCHAR2(11 BYTE) NOT NULL 
, DRIVER_PERMIT VARCHAR2(11 BYTE) NOT NULL 
, DP_ISSUE_DATE DATE 
, DP_EXPIRY_DATE DATE 
, PASSPORT_NO VARCHAR2(11 BYTE) NOT NULL 
, PP_ISSUE_DATE DATE 
, PP_EXPIRY_DATE DATE 
, BIR_NO VARCHAR2(11 BYTE) NOT NULL 
, PERMANENT_ADDR_LINE1 VARCHAR2(40 BYTE) NOT NULL 
, PERMANENT_ADDR_LINE2 VARCHAR2(40 BYTE) NOT NULL 
, PERMANENT_ADDR_LINE3 VARCHAR2(40 BYTE) NOT NULL 
, PERMANENT_ADDR_LINE4 VARCHAR2(40 BYTE) NOT NULL 
, PERMANENT_CITY VARCHAR2(40 BYTE) NOT NULL 
, PERMANENT_STATE VARCHAR2(40 BYTE) NOT NULL 
, PERMANENT_ZIP_CODE VARCHAR2(10 BYTE) NOT NULL 
, PERMANENT_COUNTRY_CODE VARCHAR2(4 BYTE) NOT NULL 
, PERMANENT_COUNTRY_DESC VARCHAR2(40 BYTE) 
, MAILING_ADDR_LINE1 VARCHAR2(40 BYTE) NOT NULL 
, MAILING_ADDR_LINE2 VARCHAR2(40 BYTE) NOT NULL 
, MAILING_ADDR_LINE3 VARCHAR2(40 BYTE) NOT NULL 
, MAILING_ADDR_LINE4 VARCHAR2(40 BYTE) NOT NULL 
, MAILING_CITY VARCHAR2(40 BYTE) NOT NULL 
, MAILING_STATE VARCHAR2(40 BYTE) NOT NULL 
, MAILING_ZIP_CODE VARCHAR2(10 BYTE) NOT NULL 
, MAILING_COUNTRY_CODE VARCHAR2(4 BYTE) NOT NULL 
, BIRTH_COUNTRY_CODE VARCHAR2(4 BYTE) NOT NULL 
, BIRTH_COUNTRY_DESC VARCHAR2(40 BYTE) 
, LOCAL_TAX_EXEMPT VARCHAR2(1 BYTE) NOT NULL 
, NATIONALITY VARCHAR2(40 BYTE) NOT NULL 
, ELIGIBLE_FOREIGN_TAX VARCHAR2(1 BYTE) NOT NULL 
, DOC_FOREIGN_TAX_EXEMPT VARCHAR2(1 BYTE) NOT NULL 
, FOREIGN_CITIZENSHIP VARCHAR2(1 BYTE) NOT NULL 
, POWER_OF_ATTORNEY VARCHAR2(1 BYTE) NOT NULL 
, CITIZEN_SHIP_COUNTRY1 VARCHAR2(4 BYTE) 
, CITIZEN_SHIP_COUNTRY2 VARCHAR2(4 BYTE) 
, CITIZEN_SHIP_COUNTRY3 VARCHAR2(4 BYTE) 
, CITIZEN_SHIP_COUNTRY4 VARCHAR2(4 BYTE) 
, RESIDENCE_TIN1 VARCHAR2(40 BYTE) 
, RESIDENCE_TIN2 VARCHAR2(40 BYTE) 
, RESIDENCE_TIN3 VARCHAR2(40 BYTE) 
, RESIDENCE_TIN4 VARCHAR2(40 BYTE) 
, EMPLOYER VARCHAR2(40 BYTE) 
, EMPLOYER_ADDRESS1 VARCHAR2(40 BYTE) 
, EMPLOYER_ADDRESS2 VARCHAR2(40 BYTE) 
, WORK_PHONE VARCHAR2(12 BYTE) 
, OCCUPATION_CODE VARCHAR2(40 BYTE) 
, RESIDENCY_CODE NUMBER(3, 0) 
, MOTHER_MAIDEN_NAME VARCHAR2(20 BYTE) NOT NULL 
, NO_OF_DEPENDENTS NUMBER(2, 0) 
, INCOME_CODE VARCHAR2(3 BYTE) 
, EDUCATION_CODE VARCHAR2(40 BYTE) 
, SHAREHOLDER_CODE VARCHAR2(4 BYTE) 
, HOME_OWNERSHIP VARCHAR2(4 BYTE) 
, STREET_TYPE VARCHAR2(2 BYTE) 
, MONTHLY_SALARY NUMBER(12, 2) 
, EMPLOYER_CITY VARCHAR2(20 BYTE) 
, MARITAL_STATUS VARCHAR2(2 BYTE) NOT NULL 
, CREATED_BY VARCHAR2(60 BYTE) NOT NULL 
, CREATION_DATE DATE NOT NULL 
, LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL 
, LAST_UPDATE_DATE DATE NOT NULL 
, OBJECT_VERSION_ID NUMBER(15, 0) NOT NULL 
, LAST_APPROVED_BY VARCHAR2(60 BYTE) NOT NULL 
, LAST_APPROVED_DATE DATE NOT NULL 
, CONSTRAINT LINCU_MEMBER_KYC_PK PRIMARY KEY 
  (
    MEMBER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LINCU_MEMBER_KYC_PK ON LINCU_MEMBER_KYC (MEMBER_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE LINCU_MEMBER_KYC
ADD CONSTRAINT LINCU_MEMBER_KYC_FK1 FOREIGN KEY
(
  MEMBER_ID 
)
REFERENCES LINCU_MEMBER_KYC
(
  MEMBER_ID 
)
ENABLE;

ALTER TABLE LINCU_MEMBER_KYC
ADD CONSTRAINT LINCU_MEMBER_KYC_FK_1 FOREIGN KEY
(
  CREDIT_UNION_ID 
, CREDIT_UNION_BRANCH_ID 
)
REFERENCES CREDIT_UNION_BRANCH
(
  CREDIT_UNION_ID 
, CREDIT_UNION_BRANCH_ID 
)
ENABLE;

CREATE TABLE LINCU_MEMBER_CARD 
(
  CARD_ID NUMBER NOT NULL 
, CREDIT_UNION_ID VARCHAR2(10 BYTE) NOT NULL 
, MEMBER_ID VARCHAR2(15 BYTE) NOT NULL 
, MEMBER_CARD_TYPE VARCHAR2(1 BYTE) 
, CARD_REQ_TYPE VARCHAR2(20 BYTE) NOT NULL 
, CREATED_BY VARCHAR2(40 BYTE) NOT NULL 
, CREATED_ON DATE NOT NULL 
, SUBMITTED_ON DATE 
, AUTHORIZED_BY VARCHAR2(40 BYTE) 
, AUTHORIZED_ON DATE 
, CARD_STATUS VARCHAR2(40 BYTE) NOT NULL 
, COMMENTS VARCHAR2(300 BYTE) 
, CONSTRAINT LINCU_MEMBER_CARD_PK PRIMARY KEY 
  (
    CARD_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LINCU_MEMBER_CARD_PK ON LINCU_MEMBER_CARD (CARD_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE SEQUENCE CARD_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE CREDIT_UNIION_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE CREDIT_UNION_BRANCH_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE MEMBER_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE USER_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;


 