CREATE TABLE COUNTRY_CODES 
(
  COUNTRY_ID VARCHAR2(20 BYTE) NOT NULL 
, COUNTRY_NAME VARCHAR2(100 BYTE) NOT NULL 
, CONSTRAINT COUNTRY_CODES_PK PRIMARY KEY 
  (
    COUNTRY_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX COUNTRY_CODES_PK ON COUNTRY_CODES (COUNTRY_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE COUNTRY_CODES
ADD CONSTRAINT COUNTRY_CODES_UK1 UNIQUE 
(
  COUNTRY_NAME 
)
USING INDEX 
(
    CREATE UNIQUE INDEX COUNTRY_CODES_UK1 ON COUNTRY_CODES (COUNTRY_NAME ASC) 
    LOGGING 
    TABLESPACE LINCU 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 65536 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      PCTINCREASE 0 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;

Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('1','TRINIDAD & TOBAGO');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('14','GRENADA, ST. VINCENT AND ST. LUCIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('19','OTHER CARIFTA COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('33','BAHAMAS AND CAYMAN ISLANDS');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('39','OTHER COMMONWEALTH');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('49','OTHER COUNTRIES');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('99','NO DECLARATION OF RESIDENCE');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('100','AFGHANISTAN');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('101','ALBANIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('102','ALGERIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('103','ANGOLA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('104','ANGUILLA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('105','ANTIGUA-BARBUDA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('106','ARGENTINA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('107','ARUBA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('108','ASCENSION');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('109','AUSTRALIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('110','AUSTRIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('111','BAHAMAS');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('112','BAHRAIN');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('113','BANGLADESH');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('114','BARBADOS');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('117','BERMUDA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('118','BOLIVIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('119','BOSNIA AND HERZEGOVINA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('120','BOTSWANA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('123','BULGARIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('124','BURKINA FASO');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('125','BURUNDI');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('126','CAMEROON');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('127','CANADA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('128','CARICOM');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('129','CAYMAN ISLANDS');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('130','CHAD');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('131','CHILE');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('132','CHINA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('133','COLOMBIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('134','CONGO');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('135','CONGO,THE DEMOCRATIC REPUBLIC');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('136','COSTA RICA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('137','CÔTE D''IVOIRE');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('138','CROATIA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('139','CUBA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('140','CYPRUS');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('141','CZECH REPUBLIC');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('142','DENMARK');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('143','DOMINICA');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME) values ('144','DOMINICAN REPUBLIC');

CREATE TABLE LINCU_ROLES 
(
  ROLE_ID NUMBER NOT NULL 
, ROLE VARCHAR2(20 BYTE) NOT NULL 
, ROLE_DESCRIPTION VARCHAR2(100 BYTE) NOT NULL 
, CONSTRAINT LINCU_ROLES_PK PRIMARY KEY 
  (
    ROLE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LINCU_USER_ROLES_PK ON LINCU_ROLES (ROLE_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE LINCU_ROLES
ADD CONSTRAINT LINCU_ROLES_UK1 UNIQUE 
(
  ROLE 
)
USING INDEX 
(
    CREATE UNIQUE INDEX LINCU_USER_ROLES_UK1 ON LINCU_ROLES (ROLE ASC) 
    LOGGING 
    TABLESPACE LINCU 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 65536 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      PCTINCREASE 0 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;

Insert into LINCU_ROLES (ROLE_ID,ROLE,ROLE_DESCRIPTION) values (1,'MSR','Member Service Representative');
Insert into LINCU_ROLES (ROLE_ID,ROLE,ROLE_DESCRIPTION) values (2,'SUP','Supervisor / Authorizer');
Insert into LINCU_ROLES (ROLE_ID,ROLE,ROLE_DESCRIPTION) values (3,'MAN_ADMIN','Administrator');
Insert into LINCU_ROLES (ROLE_ID,ROLE,ROLE_DESCRIPTION) values (4,'PREPAID_ADMIN','Prepaid Card System System Administrator');
Insert into LINCU_ROLES (ROLE_ID,ROLE,ROLE_DESCRIPTION) values (5,'FCB','FCB User');
Insert into LINCU_ROLES (ROLE_ID,ROLE,ROLE_DESCRIPTION) values (6,'LINCU_ADMIN','LinCU Administrator');

CREATE TABLE CREDIT_UNION 
(
  CREDIT_UNION_ID VARCHAR2(10 BYTE) NOT NULL 
, CREDIT_UNION_CODE VARCHAR2(2 BYTE) NOT NULL 
, CREDIT_UNION_NAME VARCHAR2(100 BYTE) NOT NULL 
, CREDIT_UNION_ADDRES_1 VARCHAR2(100 BYTE) NOT NULL 
, CREDIT_UNION_ADDRES_2 VARCHAR2(100 BYTE) 
, CREDIT_UNION_ADDRES_3 VARCHAR2(100 BYTE) 
, CREDIT_UNION_ADDRES_4 VARCHAR2(100 BYTE) 
, CREDIT_UNION_CITY VARCHAR2(100 BYTE) NOT NULL 
, CREDIT_UNION_COUNTRY VARCHAR2(100 BYTE) NOT NULL 
, CREDIT_UNION_PHONE_1 VARCHAR2(15 BYTE) NOT NULL 
, CREDIT_UNION_PHONE_2 VARCHAR2(15 BYTE) 
, CREDIT_UNION_FAX VARCHAR2(15 BYTE) 
, CREDIT_UNION_EMAIL_ID VARCHAR2(50 BYTE) NOT NULL 
, CREATED_BY VARCHAR2(60 BYTE) NOT NULL 
, CREATION_DATE DATE NOT NULL 
, LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL 
, LAST_UPDATE_DATE DATE NOT NULL 
, OBJECT_VERSION_ID NUMBER(15, 0) 
, LAST_APPROVED_BY VARCHAR2(60 BYTE) 
, LAST_APPROVED_DATE DATE 
, CONSTRAINT CREDIT_UNION_PK PRIMARY KEY 
  (
    CREDIT_UNION_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CREDIT_UNION_PK ON CREDIT_UNION (CREDIT_UNION_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE CREDIT_UNION_BRANCH 
(
  CREDIT_UNION_ID VARCHAR2(10 BYTE) NOT NULL 
, CREDIT_UNION_BRANCH_ID VARCHAR2(10 BYTE) NOT NULL 
, CREDIT_UNION_BRANCH_CODE VARCHAR2(2 BYTE) NOT NULL 
, CREDIT_UNION_BRANCH_NAME VARCHAR2(100 BYTE) NOT NULL 
, CREDIT_UNION_ADDRES_1 VARCHAR2(100 BYTE) NOT NULL 
, CREDIT_UNION_ADDRES_2 VARCHAR2(100 BYTE) 
, CREDIT_UNION_ADDRES_3 VARCHAR2(100 BYTE) 
, CREDIT_UNION_ADDRES_4 VARCHAR2(100 BYTE) 
, CREDIT_UNION_CITY VARCHAR2(100 BYTE) NOT NULL 
, CREDIT_UNION_COUNTRY VARCHAR2(100 BYTE) NOT NULL 
, CREDIT_UNION_PHONE_1 VARCHAR2(15 BYTE) NOT NULL 
, CREDIT_UNION_PHONE_2 VARCHAR2(15 BYTE) 
, CREDIT_UNION_EMAIL_ID VARCHAR2(50 BYTE) NOT NULL 
, CREATED_BY VARCHAR2(60 BYTE) NOT NULL 
, CREATION_DATE DATE NOT NULL 
, LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL 
, LAST_UPDATE_DATE DATE NOT NULL 
, OBJECT_VERSION_ID NUMBER(15, 0) 
, LAST_APPROVED_BY VARCHAR2(60 BYTE) 
, LAST_APPROVED_DATE DATE 
, CONSTRAINT CREDIT_UNION_BRANCH_PK PRIMARY KEY 
  (
    CREDIT_UNION_ID 
  , CREDIT_UNION_BRANCH_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CREDIT_UNION_BRANCH_PK ON CREDIT_UNION_BRANCH (CREDIT_UNION_ID ASC, CREDIT_UNION_BRANCH_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE CREDIT_UNION_BRANCH
ADD CONSTRAINT CREDIT_UNION_BRANCH_FK FOREIGN KEY
(
  CREDIT_UNION_ID 
)
REFERENCES CREDIT_UNION
(
  CREDIT_UNION_ID 
)
ENABLE;


ALTER TABLE LINCU_LOOKUPS
ADD CONSTRAINT LINCU_LOOKUPS_UK1 UNIQUE 
(
  LOOKUP_TYPE 
, LOOKUP_CODE 
)
USING INDEX 
(
    CREATE UNIQUE INDEX LINCU_LOOKUPS_UK1 ON LINCU_LOOKUPS (LOOKUP_TYPE ASC, LOOKUP_CODE ASC) 
    LOGGING 
    TABLESPACE LINCU 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 65536 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      PCTINCREASE 0 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;

 CREATE TABLE LINCU_LOOKUPS 
(
  LOOKUP_ID NUMBER NOT NULL 
, LOOKUP_TYPE VARCHAR2(30 BYTE) 
, LOOKUP_CODE VARCHAR2(30 BYTE) 
, LOOKUP_DESC VARCHAR2(250 BYTE) 
, CONSTRAINT LINCU_LOOKUPS_PK PRIMARY KEY 
  (
    LOOKUP_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LINCU_LOOKUPS_PK ON LINCU_LOOKUPS (LOOKUP_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE LINCU_LOOKUPS
ADD CONSTRAINT LINCU_LOOKUPS_UK1 UNIQUE 
(
  LOOKUP_TYPE 
, LOOKUP_CODE 
)
USING INDEX 
(
    CREATE UNIQUE INDEX LINCU_LOOKUPS_UK1 ON LINCU_LOOKUPS (LOOKUP_TYPE ASC, LOOKUP_CODE ASC) 
    LOGGING 
    TABLESPACE LINCU 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 65536 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      PCTINCREASE 0 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;

Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (1,'USER_TYPE_CODE','LINCU','LinCu');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (2,'USER_TYPE_CODE','FCB','FCB');
INSERT INTO LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) VALUES (64,'USER_TYPE_CODE','CREDIT_UNION','Credit Union');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (3,'SECURITY_QUESTION','FIRST_PET','Name of first pet');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (4,'SECURITY_QUESTION','FAV_PET','Name of favorite pet');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (5,'SECURITY_QUESTION','MOTHER_MAIDEN','Mother’s maiden name');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (6,'SECURITY_QUESTION','STREET_LIVED','Name of street you lived on as a child');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (7,'SECURITY_QUESTION','BIRTH_CITY','City of birth');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (8,'SECURITY_QUESTION','FAV_MOVIE','Favorite movie');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (9,'SECURITY_QUESTION','FAV_BOOK','Favorite book');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (10,'SECURITY_QUESTION','FAV_SONG','Favorite song');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (11,'CARD_TYPE','NEW_CARD','New Card');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (12,'CARD_TYPE','ADDON_CARD','Addon Card');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (13,'CARD_TYPE','TOPUP_CARD','Topup Card');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (14,'APPLICATION_STATUS','DRAFT','Draft');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (15,'APPLICATION_STATUS','SUBMITTED','Submitted');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (16,'APPLICATION_STATUS','REJECTED','Rejected');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (17,'APPLICATION_STATUS','AUTHORIZED','Authorized');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (58,'APPLICATION_STATUS','LINCU_REJECTED','LinCU Rejected');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (59,'APPLICATION_STATUS','LINCU_AUTHORIZED','LinCU Authorized');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (60,'APPLICATION_STATUS','FCB_REJECTED','FCB Rejected');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (61,'APPLICATION_STATUS','FCB_AUTHORIZED','FCB Authorized');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (62,'DOCUMENT_PROOF_TYPE','ID_PROOF','ID Proof');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (63,'DOCUMENT_PROOF_TYPE','ADDRESS_PROOF','Address Proof');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (18,'MARITAL_STATUS','D','Divorced');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (19,'MARITAL_STATUS','M','Married');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (20,'MARITAL_STATUS','S','Single');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (21,'MARITAL_STATUS','SP','Separated');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (22,'MARITAL_STATUS','W','Widow/Widower');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (23,'MARITAL_STATUS','X','Unknown');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (24,'STREET_TYPE','AV','Avenue');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (25,'STREET_TYPE','BD','Building');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (26,'STREET_TYPE','BV','Boulevard');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (27,'STREET_TYPE','CR','Circle');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (28,'STREET_TYPE','CT','Court');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (29,'STREET_TYPE','DR','Drive');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (31,'STREET_TYPE','HT','Heights');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (32,'STREET_TYPE','HY','Highway');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (33,'STREET_TYPE','LN','Lane');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (34,'STREET_TYPE','PK','Park');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (35,'STREET_TYPE','PL','Place');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (36,'STREET_TYPE','PY','Parkway');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (37,'STREET_TYPE','RD','Roadway');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (38,'STREET_TYPE','RR','Rural Route');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (39,'STREET_TYPE','ST','Street');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (40,'STREET_TYPE','TC','Terrace');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (41,'STREET_TYPE','TR','Trail');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (42,'STREET_TYPE','WY','Way');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (43,'HOME_OWNERSHIP','L','Live With Relatives');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (44,'HOME_OWNERSHIP','O','Own');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (45,'HOME_OWNERSHIP','R','Rent');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (46,'HOME_OWNERSHIP','S','Sublet');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (47,'SHAREHOLDER_CODE','MAJ','Majority Shareholder');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (48,'SHAREHOLDER_CODE','MIN','Minority Shareholder');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (49,'SHAREHOLDER_CODE','NAS','Not A Shareholder');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (50,'EDUCATION_CODE','N','NO FORMAL EDUCATION');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (51,'EDUCATION_CODE','NS','NOT SUPPLIED');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (52,'EDUCATION_CODE','P','PRIMARY LEVEL');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (53,'EDUCATION_CODE','PP','POST PRIMARY');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (54,'EDUCATION_CODE','PRO','PROFESSIONAL');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (55,'EDUCATION_CODE','SEC','SECONDARY');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (56,'EDUCATION_CODE','UNI','UNIVERSITY');
Insert into LINCU_LOOKUPS (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_DESC) values (57,'EDUCATION_CODE','VOC','VOCATIONAL');


CREATE TABLE LINCU_USER_INFO 
(
  USER_ID NUMBER(15, 0) NOT NULL 
, FIRST_NAME VARCHAR2(30 BYTE) 
, LAST_NAME VARCHAR2(30 BYTE) 
, CREDIT_UNION_ID VARCHAR2(10 BYTE) 
, CREDIT_UNION_BRANCH_ID VARCHAR2(10 BYTE) 
, USER_TYPE_CODE VARCHAR2(30 BYTE) NOT NULL 
, USER_ROLE VARCHAR2(30 BYTE) NOT NULL 
, USER_SUPERVISOR VARCHAR2(30 BYTE) 
, EMAIL VARCHAR2(60 BYTE) NOT NULL 
, MOBILE_PHONE_NUMBER VARCHAR2(20 BYTE) 
, DATE_OF_BIRTH DATE 
, GENDER VARCHAR2(1 BYTE) NOT NULL 
, CREATED_BY VARCHAR2(60 BYTE) NOT NULL 
, CREATION_DATE DATE NOT NULL 
, LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL 
, LAST_UPDATE_DATE DATE NOT NULL 
, OBJECT_VERSION_ID NUMBER(15, 0) 
, LAST_APPROVED_BY VARCHAR2(60 BYTE) 
, LAST_APPROVED_DATE DATE 
, PASSWORD VARCHAR2(300 BYTE) 
, USER_NAME VARCHAR2(60 BYTE) NOT NULL 
, SECURITY_QUSTN VARCHAR2(50 BYTE) 
, SECURITY_QUSTN_ANS VARCHAR2(250 BYTE) 
, FIRST_LOGIN_FLAG VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL 
, CONSTRAINT LINCU_USER_INFO_PK PRIMARY KEY 
  (
    USER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LINCU_USER_INFO_PK ON LINCU_USER_INFO (USER_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE LINCU_USER_INFO
ADD CONSTRAINT LINCU_USER_INFO_UK1 UNIQUE 
(
  USER_ID 
, CREDIT_UNION_ID 
, CREDIT_UNION_BRANCH_ID 
)
USING INDEX 
(
    CREATE UNIQUE INDEX LINCU_USER_INFO_UK1 ON LINCU_USER_INFO (USER_ID ASC, CREDIT_UNION_ID ASC, CREDIT_UNION_BRANCH_ID ASC) 
    LOGGING 
    TABLESPACE LINCU 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 65536 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      PCTINCREASE 0 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;

ALTER TABLE LINCU_USER_INFO
ADD CONSTRAINT USER_GENDER_CHK CHECK 
(GENDER in ('M','F'))
ENABLE;

Insert into LINCU_USER_INFO (USER_ID,FIRST_NAME,LAST_NAME,CREDIT_UNION_ID,CREDIT_UNION_BRANCH_ID,USER_TYPE_CODE,USER_ROLE,USER_SUPERVISOR,EMAIL,MOBILE_PHONE_NUMBER,DATE_OF_BIRTH,GENDER,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,OBJECT_VERSION_ID,LAST_APPROVED_BY,LAST_APPROVED_DATE,PASSWORD,USER_NAME,SECURITY_QUSTN,SECURITY_QUSTN_ANS,FIRST_LOGIN_FLAG) values (1,'Admin','Last',null,null,'LINCU','MAN_ADMIN',null,'admin@lincu.com','08297913323',to_date('13-APR-17','DD-MON-RR'),'M','seed',to_date('13-APR-17','DD-MON-RR'),'seed',to_date('13-APR-17','DD-MON-RR'),1,'test',to_date('13-APR-17','DD-MON-RR'),'a9c09df0de4c29a62502e016098de038387835b010493d78e9c8b93a3b4296b2ee7d335e26c798622091b31382f4740a044a52b5b9c939bcedf9d636248bcff5','admin@lincu.com',null,null,'N');

CREATE TABLE LINCU_MEMBER_INFO 
(
  MEMBER_ID VARCHAR2(15 BYTE) NOT NULL 
, CREDIT_UNION_ID VARCHAR2(10 BYTE) NOT NULL 
, CREDIT_UNION_BRANCH_ID VARCHAR2(10 BYTE) NOT NULL 
, MEMBER_PREFIX VARCHAR2(5 BYTE) 
, FIRST_NAME VARCHAR2(17 BYTE) NOT NULL 
, MIDDLE_NAME VARCHAR2(17 BYTE) 
, LAST_NAME VARCHAR2(30 BYTE) NOT NULL 
, DATE_OF_BIRTH DATE 
, GENDER VARCHAR2(1 BYTE) 
, EMAIL VARCHAR2(60 BYTE) 
, HOME_PHONE_NUMBER VARCHAR2(12 BYTE) 
, BUSINESS_PHONE_NUMBER VARCHAR2(12 BYTE) 
, BUSINESS_PHONE_EXTN VARCHAR2(4 BYTE) 
, MOBILE_PHONE_NUMBER VARCHAR2(12 BYTE) 
, FAX_NUMBER VARCHAR2(30 BYTE) 
, TIN_OR_SID VARCHAR2(20 BYTE) 
, CREATED_BY VARCHAR2(60 BYTE) NOT NULL 
, CREATION_DATE DATE NOT NULL 
, LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL 
, LAST_UPDATE_DATE DATE NOT NULL 
, OBJECT_VERSION_ID NUMBER(15, 0) 
, LAST_APPROVED_BY VARCHAR2(60 BYTE) 
, LAST_APPROVED_DATE DATE 
, CONSTRAINT LINCU_MEMBER_INFO_PK PRIMARY KEY 
  (
    MEMBER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LINCU_MEMBER_INFO_PK ON LINCU_MEMBER_INFO (MEMBER_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE LINCU_MEMBER_INFO
ADD CONSTRAINT LINCU_MEMBER_INFO_FK_1 FOREIGN KEY
(
  CREDIT_UNION_ID 
, CREDIT_UNION_BRANCH_ID 
)
REFERENCES CREDIT_UNION_BRANCH
(
  CREDIT_UNION_ID 
, CREDIT_UNION_BRANCH_ID 
)
ENABLE;

ALTER TABLE LINCU_MEMBER_INFO
ADD CONSTRAINT MEMBER_GENDER_CHK CHECK 
(GENDER in ('M','F'))
ENABLE;


CREATE TABLE LINCU_MEMBER_KYC 
(
  MEMBER_ID VARCHAR2(15 BYTE) NOT NULL 
, CREDIT_UNION_ID VARCHAR2(10 BYTE) NOT NULL 
, CREDIT_UNION_BRANCH_ID VARCHAR2(10 BYTE) NOT NULL 
, ELECTORIAL_ID VARCHAR2(11 BYTE) 
, DRIVER_PERMIT VARCHAR2(11 BYTE) 
, DP_ISSUE_DATE DATE 
, DP_EXPIRY_DATE DATE 
, PASSPORT_NO VARCHAR2(11 BYTE) 
, PP_ISSUE_DATE DATE 
, PP_EXPIRY_DATE DATE 
, BIR_NO VARCHAR2(11 BYTE) 
, PERMANENT_ADDR_LINE1 VARCHAR2(40 BYTE) NOT NULL 
, PERMANENT_ADDR_LINE2 VARCHAR2(40 BYTE) 
, PERMANENT_ADDR_LINE3 VARCHAR2(40 BYTE) 
, PERMANENT_ADDR_LINE4 VARCHAR2(40 BYTE) 
, PERMANENT_CITY VARCHAR2(40 BYTE) NOT NULL 
, PERMANENT_STATE VARCHAR2(40 BYTE) 
, PERMANENT_ZIP_CODE VARCHAR2(10 BYTE) 
, PERMANENT_COUNTRY_CODE VARCHAR2(4 BYTE) NOT NULL 
, PERMANENT_COUNTRY_DESC VARCHAR2(40 BYTE) 
, MAILING_ADDR_LINE1 VARCHAR2(40 BYTE) NOT NULL 
, MAILING_ADDR_LINE2 VARCHAR2(40 BYTE) 
, MAILING_ADDR_LINE3 VARCHAR2(40 BYTE) 
, MAILING_ADDR_LINE4 VARCHAR2(40 BYTE) 
, MAILING_CITY VARCHAR2(40 BYTE) NOT NULL 
, MAILING_STATE VARCHAR2(40 BYTE) 
, MAILING_ZIP_CODE VARCHAR2(10 BYTE) 
, MAILING_COUNTRY_CODE VARCHAR2(4 BYTE) NOT NULL 
, BIRTH_COUNTRY_CODE VARCHAR2(4 BYTE) NOT NULL 
, BIRTH_COUNTRY_DESC VARCHAR2(40 BYTE) 
, LOCAL_TAX_EXEMPT VARCHAR2(1 BYTE) NOT NULL 
, NATIONALITY VARCHAR2(4 BYTE) NOT NULL 
, ELIGIBLE_FOREIGN_TAX VARCHAR2(1 BYTE) NOT NULL 
, DOC_FOREIGN_TAX_EXEMPT VARCHAR2(1 BYTE) NOT NULL 
, FOREIGN_CITIZENSHIP VARCHAR2(1 BYTE) NOT NULL 
, POWER_OF_ATTORNEY VARCHAR2(1 BYTE) NOT NULL 
, CITIZEN_SHIP_COUNTRY1 VARCHAR2(4 BYTE) 
, CITIZEN_SHIP_COUNTRY2 VARCHAR2(4 BYTE) 
, CITIZEN_SHIP_COUNTRY3 VARCHAR2(4 BYTE) 
, CITIZEN_SHIP_COUNTRY4 VARCHAR2(4 BYTE) 
, RESIDENCE_TIN1 VARCHAR2(40 BYTE) 
, RESIDENCE_TIN2 VARCHAR2(40 BYTE) 
, RESIDENCE_TIN3 VARCHAR2(40 BYTE) 
, RESIDENCE_TIN4 VARCHAR2(40 BYTE) 
, EMPLOYER VARCHAR2(40 BYTE) 
, EMPLOYER_ADDRESS1 VARCHAR2(40 BYTE) 
, EMPLOYER_ADDRESS2 VARCHAR2(40 BYTE) 
, WORK_PHONE VARCHAR2(12 BYTE) 
, OCCUPATION_CODE VARCHAR2(3 BYTE) NOT NULL 
, RESIDENCY_CODE NUMBER(3, 0) 
, MOTHER_MAIDEN_NAME VARCHAR2(20 BYTE) NOT NULL 
, NO_OF_DEPENDENTS NUMBER(2, 0) 
, INCOME_CODE VARCHAR2(3 BYTE) 
, EDUCATION_CODE VARCHAR2(4 BYTE) 
, SHAREHOLDER_CODE VARCHAR2(4 BYTE) 
, HOME_OWNERSHIP VARCHAR2(4 BYTE) 
, STREET_TYPE VARCHAR2(2 BYTE) 
, MONTHLY_SALARY NUMBER(12, 2) 
, EMPLOYER_CITY VARCHAR2(20 BYTE) 
, MARITAL_STATUS VARCHAR2(2 BYTE) NOT NULL 
, CREATED_BY VARCHAR2(60 BYTE) NOT NULL 
, CREATION_DATE DATE NOT NULL 
, LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL 
, LAST_UPDATE_DATE DATE NOT NULL 
, OBJECT_VERSION_ID NUMBER(15, 0) 
, LAST_APPROVED_BY VARCHAR2(60 BYTE) 
, LAST_APPROVED_DATE DATE 
, CONSTRAINT LINCU_MEMBER_KYC_PK PRIMARY KEY 
  (
    MEMBER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LINCU_MEMBER_KYC_PK ON LINCU_MEMBER_KYC (MEMBER_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE LINCU_MEMBER_KYC
ADD CONSTRAINT LINCU_MEMBER_KYC_FK1 FOREIGN KEY
(
  MEMBER_ID 
)
REFERENCES LINCU_MEMBER_KYC
(
  MEMBER_ID 
)
ENABLE;

ALTER TABLE LINCU_MEMBER_KYC
ADD CONSTRAINT LINCU_MEMBER_KYC_FK_1 FOREIGN KEY
(
  CREDIT_UNION_ID 
, CREDIT_UNION_BRANCH_ID 
)
REFERENCES CREDIT_UNION_BRANCH
(
  CREDIT_UNION_ID 
, CREDIT_UNION_BRANCH_ID 
)
ENABLE;

CREATE TABLE LINCU_MEMBER_CARD 
(
  CARD_ID NUMBER NOT NULL 
, CREDIT_UNION_ID VARCHAR2(10 BYTE) NOT NULL 
, MEMBER_ID VARCHAR2(15 BYTE) NOT NULL 
, CARD_REQ_TYPE VARCHAR2(20 BYTE) NOT NULL 
, CREATED_BY VARCHAR2(40 BYTE) NOT NULL 
, CREATED_ON DATE NOT NULL 
, SUBMITTED_ON DATE 
, AUTHORIZED_BY VARCHAR2(40 BYTE) 
, AUTHORIZED_ON DATE 
, CARD_STATUS VARCHAR2(40 BYTE) NOT NULL 
, COMMENTS VARCHAR2(300 BYTE) 
, BATCH_NUMBER NUMBER 
, LINCU_COMMENTS VARCHAR2(20 BYTE) 
, FCB_COMMENTS VARCHAR2(20 BYTE) 
, ADMIN_COMMENTS VARCHAR2(20 BYTE) 
, SUP_COMMENTS VARCHAR2(300 BYTE) 
, CONSTRAINT LINCU_MEMBER_CARD_PK PRIMARY KEY 
  (
    CARD_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LINCU_MEMBER_CARD_PK ON LINCU_MEMBER_CARD (CARD_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE LINCU_MEMBER_CARD_DOCS 
(
  DOC_ID NUMBER NOT NULL 
, CARD_ID NUMBER NOT NULL 
, DOC_DESC VARCHAR2(250 BYTE) 
, DOCUMENT BLOB 
, DOCUMENT_NAME VARCHAR2(100 BYTE) 
, REQUIRED VARCHAR2(1 BYTE) NOT NULL 
, DOCUMENT_TYPE VARCHAR2(30 BYTE) 
, CONSTRAINT LINCU_MEMBER_CARD_DOCS_PK PRIMARY KEY 
  (
    DOC_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LINCU_MEMBER_CARD_DOCS_PK ON LINCU_MEMBER_CARD_DOCS (DOC_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL 
LOB (DOCUMENT) STORE AS SYS_LOB0000025796C00004$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE LINCU 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 65536 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    PCTINCREASE 0 
    BUFFER_POOL DEFAULT 
  )  
);

ALTER TABLE LINCU_MEMBER_CARD_DOCS
ADD CONSTRAINT LINCU_MEMBER_CARD_DOCS_FK1 FOREIGN KEY
(
  CARD_ID 
)
REFERENCES LINCU_MEMBER_CARD
(
  CARD_ID 
)
ENABLE;

CREATE TABLE LINCU_MEMBER_CARD_AUDIT 
(
  CARD_ID NUMBER NOT NULL 
, LINCU_ID VARCHAR2(10 BYTE) NOT NULL 
, MEMBER_ID VARCHAR2(15 BYTE) NOT NULL 
, CARD_REQ_TYPE VARCHAR2(20 BYTE) NOT NULL 
, CARD_AUDIT_ID NUMBER NOT NULL 
, UPDATED_BY VARCHAR2(20 BYTE) NOT NULL 
, UPDATED_DATE DATE NOT NULL 
, COMMENTS VARCHAR2(300 BYTE) 
, CREDIT_UNION_ID VARCHAR2(10 BYTE) 
, STATUS VARCHAR2(40 BYTE) NOT NULL 
, CONSTRAINT LINCU_MEMBER_CARD_AUDIT_PK PRIMARY KEY 
  (
    CARD_AUDIT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LINCU_MEMBER_CARD_AUDIT_PK ON LINCU_MEMBER_CARD_AUDIT (CARD_AUDIT_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE LINCU_MEMBER_CARD_AUDIT
ADD CONSTRAINT LINCU_MEMBER_CARD_AUDIT_FK1 FOREIGN KEY
(
  CARD_ID 
)
REFERENCES LINCU_MEMBER_CARD
(
  CARD_ID 
)
ENABLE;


CREATE TABLE OCCUPATION_CODES 
(
  OCCUPATION_ID VARCHAR2(3 BYTE) NOT NULL 
, OCCUPATION_DES VARCHAR2(100 BYTE) NOT NULL 
, CONSTRAINT OCCUPATION_CODES_PK PRIMARY KEY 
  (
    OCCUPATION_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OCCUPATION_CODES_PK ON OCCUPATION_CODES (OCCUPATION_ID ASC) 
      LOGGING 
      TABLESPACE LINCU 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE LINCU 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('1','Technical');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('2','Professional');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('24','UNEMPLOYED');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('25','Accountant');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('0','N/A');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('26','Actuary');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('27','Administrator');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('28','Anesthesiologist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('29','Analyst');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('30','Architect');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('31','Artist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('32','Athlete');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('33','Attorney at Law');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('35','Auditor');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('34','Author');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('36','Administrative Assistant');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('37','Bailiff');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('38','Baker');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('39','Banker');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('40','Bank Manager');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('41','Bartender');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('42','Beautician');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('43','Biochemist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('44','Bishop');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('445','Builder');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('46','Business Analyst');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('47','Businessman');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('48','Carpenter');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('49','CEO (Chief Executive Officer)');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('50','CFO (Chief Financial Officer)');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('51','CIO ( Chief Information Officer)');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('52','Caregiver');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('53','Chef');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('54','Cook');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('55','Civil Engineer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('56','Cleaner');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('57','Clerk');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('58','Coach');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('59','Coast Guard');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('60','Computer Engineer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('61','Computer Programmer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('62','Construction Manager');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('63','Construction Worker');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('64','Consultant');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('65','Corporate Executive Officer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('66','Cosmetologist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('67','Courier');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('68','Craftsman / Craftswoman');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('69','Customs Officer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('70','Database Administrator');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('71','Dentist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('72','Dermatologist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('73','Designer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('74','Dietician');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('75','Diplomat');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('76','Disc Jockey');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('77','Doctor (PhD)');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('78','Doctor (MD)');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('79','Domestic Worker');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('80','Draftsman');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('81','Dressmaker');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('82','Driver');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('83','Economist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('84','Editor');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('85','Electrician');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('86','Engineer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('87','Entertainer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('88','Entrepreneur');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('89','Estate Agent');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('90','Executive');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('91','Farmer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('92','Financial Planner');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('93','Fire Officer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('94','Flight Attendant');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('95','Florist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('96','Gardener');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('97','Gynecologist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('98','Hairdresser');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('99','Handyman');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('100','Herbalist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('101','Horse Trainer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('102','Housewife');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('103','HR Manager');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('104','Jurist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('105','Judge');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('106','Lab Technician');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('107','Labourer (Skilled / Unskilled)');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('108','Lawyer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('109','Lifeguard');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('110','Linesman');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('111','Locksmith');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('112','Magistrate');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('113','Mason');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('114','Masseuse');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('115','Mechanic');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('116','Mechanical Engineer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('117','Meteorologist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('118','Military Personnel');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('119','Nun');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('120','Nurse');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('121','Office Assistant');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('122','Ophthalmologist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('123','Orthodontist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('124','Painter');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('125','Paramedic');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('126','Pathologist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('127','Pediatrician');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('128','Pharmacist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('129','Pastor');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('130','Pilot');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('131','Plumber');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('132','Police Officer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('133','Politician');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('134','Public Relations Officer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('135','Public Servant');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('136','Publisher');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('137','Professor');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('138','Real Estate Agent');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('139','Receptionist');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('140','Retired');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('141','Salesman / Saleswoman');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('142','Sanitation Worker');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('143','School Principal');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('144','Seamstress');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('145','Self Employed');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('146','Secretary');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('147','Social Worker');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('148','Software Engineer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('149','Stock Broker');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('150','Street Vendor');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('151','Student');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('152','Surgeon');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('153','Surveyor');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('154','System Administrator');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('155','Systems Designer');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('156','Systems Analyst');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('157','Tailor');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('158','Taxi-driver');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('159','Teacher');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('160','Technician');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('161','Telephone Operator');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('162','Tradesman');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('163','Undertaker');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('164','Veterinarian');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('165','Waiter/Waitress');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('166','Welder');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('167','X-ray Technician');
Insert into OCCUPATION_CODES (OCCUPATION_ID,OCCUPATION_DES) values ('168','Zoologist');


CREATE SEQUENCE CARD_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE CREDIT_UNIION_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE CREDIT_UNION_BRANCH_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE MEMBER_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE USER_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE MEMBER_CARD_DOCS_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE BATCH_NUMBER_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE CARD_AUDIT_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

ALTER TABLE LINCU_MEMBER_CARD 
ADD (REF_CARD_ID NUMBER );

ALTER TABLE LINCU_MEMBER_CARD 
ADD (TOPUP_AMOUNT NUMBER );


INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('65', 'PREFIX', 'DR', 'Dr.');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('66', 'PREFIX', 'MESRS', 'Messers.');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('67', 'PREFIX', 'MISS', 'Miss.');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('68', 'PREFIX', 'MR', 'Mr.');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('69', 'PREFIX', 'MRS', 'Mrs.');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('70', 'PREFIX', 'MS', 'Ms.');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('71', 'PREFIX', 'PROF', 'Prof.');

ALTER TABLE LINCU_MEMBER_CARD 
ADD (ACTIVE VARCHAR2(1) );

ALTER TABLE CREDIT_UNION 
ADD (ACTIVE VARCHAR2(1) );

ALTER TABLE CREDIT_UNION_BRANCH 
ADD (ACTIVE VARCHAR2(1) );

ALTER TABLE LINCU_USER_INFO 
ADD (ACTIVE VARCHAR2(1) );

ALTER TABLE LINCU_MEMBER_INFO 
ADD (ACTIVE VARCHAR2(1) );

ALTER TABLE LINCU_MEMBER_KYC 
ADD (ACTIVE VARCHAR2(1) );

ALTER TABLE LINCU_MEMBER_INFO 
ADD (STATUS VARCHAR2(40) );

ALTER TABLE LINCU_MEMBER_KYC 
ADD (STATUS VARCHAR2(40) );

ALTER TABLE LINCU_MEMBER_INFO 
ADD (COMMENTS VARCHAR2(250) );

INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('72', 'MEMBER_STATUS', 'DRAFT', 'Draft');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('75', 'MEMBER_STATUS', 'SUBMIT', 'Submitted');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('73', 'MEMBER_STATUS', 'APPROVE', 'Approved');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('74', 'MEMBER_STATUS', 'REJECT', 'Rejected');

ALTER TABLE CREDIT_UNION  
MODIFY (CREDIT_UNION_CODE VARCHAR2(7 BYTE) );

ALTER TABLE CREDIT_UNION_BRANCH  
MODIFY (CREDIT_UNION_BRANCH_CODE VARCHAR2(3 BYTE) );

ALTER TABLE LINCU_MEMBER_CARD 
ADD (APPLICATION_NO VARCHAR2(10) );

ALTER TABLE LINCU_MEMBER_CARD  
MODIFY (LINCU_COMMENTS VARCHAR2(300 BYTE) );

ALTER TABLE LINCU_MEMBER_CARD  
MODIFY (FCB_COMMENTS VARCHAR2(300 BYTE) );

ALTER TABLE LINCU_MEMBER_CARD  
MODIFY (ADMIN_COMMENTS VARCHAR2(300 BYTE) );


INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('76', 'DOCUMENT_PROOF_TYPE', 'INCOME_PROOF', 'Income Proof');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('77', 'DOCUMENT_PROOF_TYPE', 'OTHER_PROOF', 'Other Proofs');

-------------------

INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('78', 'CURRENCY', '0', 'LESS THAN $10,000');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('79', 'CURRENCY', '1', '$10,000 - $19,999');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('80', 'CURRENCY', '2', '$20,000 - $29,999');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('81', 'CURRENCY', '3', '$30,000 - $39,999');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('82', 'CURRENCY', '4', '$40,000 - $49,999');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('83', 'CURRENCY', '5', '$50,000 - $59,999');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('84', 'CURRENCY', '6', '$60,000 - $69,000');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('85', 'CURRENCY', '7', '$70,000 - $79,999');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('86', 'CURRENCY', '8', '$80,000 - $89,999');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('87', 'CURRENCY', '9', '$90,000 - $99,000');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('88', 'CURRENCY', '10', '$100,000 - $149,999');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('89', 'CURRENCY', '11', '$$150,000 - $199,999');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('90', 'CURRENCY', '12', '$200,000 - $299,999');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('91', 'CURRENCY', '13', '$300,000 - $399,000');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('92', 'CURRENCY', '14', '$400,000 - $499,999');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('93', 'CURRENCY', '15', '$500,000. PLUS');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('94', 'CURRENCY', '16', 'NOT SUPPLIED');

ALTER TABLE LINCU_MEMBER_INFO 
ADD (MEMBER_NO VARCHAR2(50) );

ALTER TABLE LINCU_MEMBER_KYC  
MODIFY (MONTHLY_SALARY VARCHAR2(5) );

ALTER TABLE LINCU_USER_INFO  
MODIFY (USER_SUPERVISOR NUMBER(15) );

ALTER TABLE LINCU_USER_INFO 
ADD (PASSWORD1 VARCHAR2(300) );

ALTER TABLE LINCU_USER_INFO 
ADD (PASSWORD2 VARCHAR2(300) );

ALTER TABLE LINCU_USER_INFO 
ADD (PASSWORD3 VARCHAR2(300) );

ALTER TABLE LINCU_USER_INFO 
ADD (PASSWORD4 VARCHAR2(300) );

DELETE FROM "LINCUDB"."LINCU_LOOKUPS" WHERE LOOKUP_TYPE = 'PREFIX';
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('65', 'PREFIX', 'MR', 'MR');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('66', 'PREFIX', 'MS', 'MS');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('67', 'PREFIX', 'MRS', 'MRS');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('68', 'PREFIX', 'MISS', 'MISS');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('69', 'PREFIX', 'DR', 'DR');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('70', 'PREFIX', 'REV', 'REV');
INSERT INTO "LINCUDB"."LINCU_LOOKUPS" (LOOKUP_ID, LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_DESC) VALUES ('71', 'PREFIX', 'HON', 'HON');

ALTER TABLE LINCU_MEMBER_KYC RENAME COLUMN INCOME_CODE TO ANNUAL_INCOME;

ALTER TABLE LINCU_MEMBER_KYC  
MODIFY (MONTHLY_SALARY NUMBER );

ALTER TABLE COUNTRY_CODES 
ADD (CODE_TYPE VARCHAR2(20) );

DELETE FROM COUNTRY_CODES;

Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('145','DUBAI','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('146','ECUADOR','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('147','EGYPT','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('148','EL SALVADOR','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('149','ETHIOPIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('150','FALKLAND ISLANDS (MALVINAS)','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('151','FIJI','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('152','FINLAND','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('153','FRANCE','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('154','FRENCH GUIANA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('155','FRENCH POLYNESIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('156','GAMBIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('157','GERMANY','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('158','GHANA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('159','GIBRALTAR','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('160','GREAT BRITAIN','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('161','GREECE','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('162','GREENLAND','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('163','GRENADA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('164','GUADELOUPE','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('165','GUATEMALA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('166','GUYANA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('167','HAITI','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('168','HOLY SEE (VATICAN CITY STATE)','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('169','HONDURAS','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('170','HUNGARY','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('171','ICELAND','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('172','INDIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('173','INDONESIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('174','IRAN','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('175','IRAQ','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('176','IRELAND','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('177','ISRAEL','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('178','ITALY','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('179','JAMAICA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('180','JAPAN','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('181','JORDAN','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('182','KENYA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('183','KUWAIT','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('184','LAOS','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('185','LEBANON','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('186','LESOTHO','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('187','LIBERIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('188','LIBYA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('189','LIECHTENSTEIN','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('190','LITHUANIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('191','LUXEMBOURG','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('192','MACAO','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('193','MADAGASCAR','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('194','MADEIRA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('195','MALAWI','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('196','MALAYSIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('197','MALDIVES','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('198','MALI','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('199','MALTA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('200','MARTINIQUE','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('201','MAURITANIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('202','MAURITIUS','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('203','MEXICO','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('204','MONACO','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('205','MONGOLIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('206','MONTSERRAT','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('207','MOROCCO','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('208','MOZAMBIQUE','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('209','MYANMAR','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('210','NAMIBIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('211','NEPAL','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('212','NETHERLANDS','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('213','NETHERLANDS ANTILLES','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('214','NEW CALEDONIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('215','NEW ZEALAND','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('216','NICARAGUA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('217','NIGER','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('218','NIGERIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('219','NORTH KOREA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('220','NORWAY','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('221','OMAN','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('222','PAKISTAN','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('223','PANAMA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('224','PAPUA NEW GUINEA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('225','PARAGUAY','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('226','PERU','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('227','PHILIPPINES','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('228','POLAND','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('229','PORTUGAL','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('230','PUERTO RICO','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('231','QATAR','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('232','REPUBLIC OF MOLDOVA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('233','ROMANIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('234','RUSSIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('235','RWANDA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('236','SAUDI ARABIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('237','SENEGAL','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('238','SEYCHELLES','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('239','SINGAPORE','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('240','SLOVAKIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('241','SLOVENIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('242','SOUTH AFRICA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('243','SOUTH KOREA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('244','SPAIN','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('245','SRI LANKA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('246','ST. KITTS NEVIS','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('247','ST. LUCIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('248','ST. PIERRE AND MIQUELON','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('249','ST. VINCENT AND THE GRENADINES','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('250','SUDAN','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('251','SURINAME','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('252','SWAZILAND','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('253','SWEDEN','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('254','SWITZERLAND','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('255','SYRIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('256','TAIWAN','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('257','TANZANIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('258','THAILAND','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('259','TOGO','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('260','TONGA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('261','TUNISIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('262','TURKEY','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('263','TURKS AND CAICOS ISLANDS','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('264','UGANDA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('265','UKRAINE','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('266','UNITED ARAB EMIRATES','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('267','UNITED KINGDOM','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('268','URUGUAY','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('269','USA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('270','VANUATU','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('271','VENEZUELA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('272','VIET NAM','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('273','VIRGIN ISLANDS, U.S.','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('274','WEST INDIES','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('275','WESTERN SAMOA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('276','YEMEN','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('277','ZAIRE','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('278','ZAMBIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('279','ZIMBABWE','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('AD','Andorra','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('AE','United Arab Emirates','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('AF','Afghanistan','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('AG','Antigua and Barbuda','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('AI','Anguilla','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('AL','Albania','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('AM','Armenia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('AO','Angola','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('AQ','Antarctica','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('AR','Argentina','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('AS','American Samoa','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('AT','Austria','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('AU','Australia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('AW','Aruba','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('AX','Aland Islands !Åland Islands','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('AZ','Azerbaijan','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BA','Bosnia and Herzegovina','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BB','Barbados','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BD','Bangladesh','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BE','Belgium','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BF','Burkina Faso','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BG','Bulgaria','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BH','Bahrain','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BI','Burundi','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BJ','Benin','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BL','Saint Barthélemy','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BM','Bermuda','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BN','Brunei Darussalam','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BO','Bolivia, Plurinational State of','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BQ','Bonaire, Sint Eustatius and Saba','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BR','Brazil','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BS','Bahamas','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BT','Bhutan','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BV','Bouvet Island','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BW','Botswana','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BY','Belarus','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('BZ','Belize','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CA','Canada','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CC','Cocos (Keeling) Islands','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CD','Congo, the Democratic Republic of the','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CF','Central African Republic','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CG','Congo','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CH','Switzerland','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CI','Cote d''Ivoire !Côte d''Ivoire','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CK','Cook Islands','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CL','Chile','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CM','Cameroon','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CN','China','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CO','Colombia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CR','Costa Rica','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CU','Cuba','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CV','Cabo Verde','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CW','Curaçao','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CX','Christmas Island','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CY','Cyprus','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('CZ','Czechia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('DE','Germany','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('DJ','Djibouti','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('DK','Denmark','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('DM','Dominica','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('DO','Dominican Republic','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('DZ','Algeria','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('EC','Ecuador','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('EE','Estonia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('EG','Egypt','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('EH','Western Sahara','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('ER','Eritrea','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('ES','Spain','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('ET','Ethiopia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('FI','Finland','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('FJ','Fiji','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('FK','Falkland Islands (Malvinas)','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('FM','Micronesia, Federated States of','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('FO','Faroe Islands','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('FR','France','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GA','Gabon','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GB','United Kingdom of Great Britain and Northern Ireland','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GD','Grenada','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GE','Georgia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GF','French Guiana','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GG','Guernsey','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GH','Ghana','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GI','Gibraltar','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GL','Greenland','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GM','Gambia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GN','Guinea','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GP','Guadeloupe','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GQ','Equatorial Guinea','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GR','Greece','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GS','South Georgia and the South Sandwich Islands','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GT','Guatemala','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GU','Guam','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GW','Guinea-Bissau','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('GY','Guyana','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('HK','Hong Kong','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('HM','Heard Island and McDonald Islands','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('HN','Honduras','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('HR','Croatia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('HT','Haiti','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('HU','Hungary','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('ID','Indonesia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('IE','Ireland','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('IL','Israel','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('IM','Isle of Man','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('IN','India','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('IO','British Indian Ocean Territory','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('IQ','Iraq','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('IR','Iran, Islamic Republic of','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('IS','Iceland','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('IT','Italy','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('JE','Jersey','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('JM','Jamaica','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('JO','Jordan','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('JP','Japan','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('KE','Kenya','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('KG','Kyrgyzstan','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('KH','Cambodia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('KI','Kiribati','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('KM','Comoros','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('KN','Saint Kitts and Nevis','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('KP','Korea, Democratic People''s Republic of','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('KR','Korea, Republic of','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('KW','Kuwait','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('KY','Cayman Islands','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('KZ','Kazakhstan','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('LA','Lao People''s Democratic Republic','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('LB','Lebanon','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('LC','Saint Lucia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('LI','Liechtenstein','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('LK','Sri Lanka','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('LR','Liberia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('LS','Lesotho','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('LT','Lithuania','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('LU','Luxembourg','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('LV','Latvia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('LY','Libya','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MA','Morocco','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MC','Monaco','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MD','Moldova, Republic of','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('ME','Montenegro','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MF','Saint Martin (French part)','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MG','Madagascar','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MH','Marshall Islands','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MK','Macedonia, the former Yugoslav Republic of','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('ML','Mali','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MM','Myanmar','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MN','Mongolia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MO','Macao','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MP','Northern Mariana Islands','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MQ','Martinique','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MR','Mauritania','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MS','Montserrat','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MT','Malta','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MU','Mauritius','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MV','Maldives','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MW','Malawi','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MX','Mexico','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MY','Malaysia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('MZ','Mozambique','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('NA','Namibia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('NC','New Caledonia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('NE','Niger','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('NF','Norfolk Island','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('NG','Nigeria','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('NI','Nicaragua','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('NL','Netherlands','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('NO','Norway','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('1','TRINIDAD & TOBAGO','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('14','GRENADA, ST. VINCENT AND ST. LUCIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('19','OTHER CARIFTA COUNTRY','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('33','BAHAMAS AND CAYMAN ISLANDS','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('39','OTHER COMMONWEALTH','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('49','OTHER COUNTRIES','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('99','NO DECLARATION OF RESIDENCE','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('100','AFGHANISTAN','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('101','ALBANIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('102','ALGERIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('103','ANGOLA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('104','ANGUILLA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('105','ANTIGUA-BARBUDA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('106','ARGENTINA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('107','ARUBA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('108','ASCENSION','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('109','AUSTRALIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('110','AUSTRIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('111','BAHAMAS','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('112','BAHRAIN','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('113','BANGLADESH','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('114','BARBADOS','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('117','BERMUDA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('118','BOLIVIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('119','BOSNIA AND HERZEGOVINA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('120','BOTSWANA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('123','BULGARIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('124','BURKINA FASO','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('125','BURUNDI','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('126','CAMEROON','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('127','CANADA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('128','CARICOM','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('129','CAYMAN ISLANDS','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('130','CHAD','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('131','CHILE','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('132','CHINA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('133','COLOMBIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('134','CONGO','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('135','CONGO,THE DEMOCRATIC REPUBLIC','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('136','COSTA RICA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('137','CÔTE D''IVOIRE','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('138','CROATIA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('139','CUBA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('140','CYPRUS','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('141','CZECH REPUBLIC','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('142','DENMARK','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('143','DOMINICA','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('144','DOMINICAN REPUBLIC','RESIDENCY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('NP','Nepal','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('NR','Nauru','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('NU','Niue','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('NZ','New Zealand','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('OM','Oman','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('PA','Panama','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('PE','Peru','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('PF','French Polynesia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('PG','Papua New Guinea','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('PH','Philippines','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('PK','Pakistan','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('PL','Poland','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('PM','Saint Pierre and Miquelon','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('PN','Pitcairn','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('PR','Puerto Rico','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('PS','Palestine, State of','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('PT','Portugal','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('PW','Palau','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('PY','Paraguay','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('QA','Qatar','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('RE','Reunion !Réunion','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('RO','Romania','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('RS','Serbia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('RU','Russian Federation','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('RW','Rwanda','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SA','Saudi Arabia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SB','Solomon Islands','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SC','Seychelles','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SD','Sudan','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SE','Sweden','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SG','Singapore','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SH','Saint Helena, Ascension and Tristan da Cunha','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SI','Slovenia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SJ','Svalbard and Jan Mayen','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SK','Slovakia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SL','Sierra Leone','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SM','San Marino','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SN','Senegal','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SO','Somalia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SR','Suriname','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SS','South Sudan','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('ST','Sao Tome and Principe','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SV','El Salvador','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SX','Sint Maarten (Dutch part)','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SY','Syrian Arab Republic','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('SZ','Swaziland','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('TC','Turks and Caicos Islands','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('TD','Chad','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('TF','French Southern Territories','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('TG','Togo','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('TH','Thailand','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('TJ','Tajikistan','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('TK','Tokelau','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('TL','Timor-Leste','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('TM','Turkmenistan','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('TN','Tunisia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('TO','Tonga','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('TR','Turkey','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('TT','Trinidad and Tobago','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('TV','Tuvalu','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('TW','Taiwan, Province of China','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('TZ','Tanzania, United Republic of','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('UA','Ukraine','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('UG','Uganda','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('UM','United States Minor Outlying Islands','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('US','United States of America','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('UY','Uruguay','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('UZ','Uzbekistan','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('VA','Holy See','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('VC','Saint Vincent and the Grenadines','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('VE','Venezuela, Bolivarian Republic of','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('VG','Virgin Islands, British','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('VI','Virgin Islands, U.S.','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('VN','Viet Nam','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('VU','Vanuatu','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('WF','Wallis and Futuna','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('WS','Samoa','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('YE','Yemen','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('YT','Mayotte','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('ZA','South Africa','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('ZM','Zambia','COUNTRY');
Insert into COUNTRY_CODES (COUNTRY_ID,COUNTRY_NAME,CODE_TYPE) values ('ZW','Zimbabwe','COUNTRY');


