package com.linCu.model.entity;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 14 02:00:31 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LincuUserInfoEOImpl extends EntityImpl {

    /**
     * Validation method for CreditUnionId.
     */
    public boolean validateCreditUnionId(String creditunionid) {
        if((this.getUserTypeCode() != null) && ("CREDIT_UNION".equalsIgnoreCase(this.getUserTypeCode())) && (creditunionid == null)){
        return false;
        }else{
            return true;
        }
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        UserId,
        FirstName,
        LastName,
        CreditUnionId,
        CreditUnionBranchId,
        UserTypeCode,
        UserRole,
        UserSupervisor,
        Email,
        MobilePhoneNumber,
        DateOfBirth,
        Gender,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        ObjectVersionId,
        LastApprovedBy,
        LastApprovedDate,
        Password,
        UserName,
        SecurityQustn,
        SecurityQustnAns,
        FirstLoginFlag,
        SecurityQustn1,
        SecurityQustnAns1,
        SecurityQustn2,
        SecurityQustnAns2,
        SecurityQustn3,
        SecurityQustnAns3,
        SecurityQustn4,
        SecurityQustnAns4,
        Active,
        CreditUnionBranchEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int USERID = AttributesEnum.UserId.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int CREDITUNIONID = AttributesEnum.CreditUnionId.index();
    public static final int CREDITUNIONBRANCHID = AttributesEnum.CreditUnionBranchId.index();
    public static final int USERTYPECODE = AttributesEnum.UserTypeCode.index();
    public static final int USERROLE = AttributesEnum.UserRole.index();
    public static final int USERSUPERVISOR = AttributesEnum.UserSupervisor.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int MOBILEPHONENUMBER = AttributesEnum.MobilePhoneNumber.index();
    public static final int DATEOFBIRTH = AttributesEnum.DateOfBirth.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int OBJECTVERSIONID = AttributesEnum.ObjectVersionId.index();
    public static final int LASTAPPROVEDBY = AttributesEnum.LastApprovedBy.index();
    public static final int LASTAPPROVEDDATE = AttributesEnum.LastApprovedDate.index();
    public static final int PASSWORD = AttributesEnum.Password.index();
    public static final int USERNAME = AttributesEnum.UserName.index();
    public static final int SECURITYQUSTN = AttributesEnum.SecurityQustn.index();
    public static final int SECURITYQUSTNANS = AttributesEnum.SecurityQustnAns.index();
    public static final int FIRSTLOGINFLAG = AttributesEnum.FirstLoginFlag.index();
    public static final int SECURITYQUSTN1 = AttributesEnum.SecurityQustn1.index();
    public static final int SECURITYQUSTNANS1 = AttributesEnum.SecurityQustnAns1.index();
    public static final int SECURITYQUSTN2 = AttributesEnum.SecurityQustn2.index();
    public static final int SECURITYQUSTNANS2 = AttributesEnum.SecurityQustnAns2.index();
    public static final int SECURITYQUSTN3 = AttributesEnum.SecurityQustn3.index();
    public static final int SECURITYQUSTNANS3 = AttributesEnum.SecurityQustnAns3.index();
    public static final int SECURITYQUSTN4 = AttributesEnum.SecurityQustn4.index();
    public static final int SECURITYQUSTNANS4 = AttributesEnum.SecurityQustnAns4.index();
    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int CREDITUNIONBRANCHEO = AttributesEnum.CreditUnionBranchEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LincuUserInfoEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.linCu.model.entity.LincuUserInfoEO");
    }


    /**
     * Gets the attribute value for UserId, using the alias name UserId.
     * @return the value of UserId
     */
    public Long getUserId() {
        return (Long) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserId.
     * @param value value to set the UserId
     */
    public void setUserId(Long value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for FirstName, using the alias name FirstName.
     * @return the value of FirstName
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FirstName.
     * @param value value to set the FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for LastName, using the alias name LastName.
     * @return the value of LastName
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastName.
     * @param value value to set the LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for CreditUnionId, using the alias name CreditUnionId.
     * @return the value of CreditUnionId
     */
    public String getCreditUnionId() {
        return (String) getAttributeInternal(CREDITUNIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreditUnionId.
     * @param value value to set the CreditUnionId
     */
    public void setCreditUnionId(String value) {
        setAttributeInternal(CREDITUNIONID, value);
    }

    /**
     * Gets the attribute value for CreditUnionBranchId, using the alias name CreditUnionBranchId.
     * @return the value of CreditUnionBranchId
     */
    public String getCreditUnionBranchId() {
        return (String) getAttributeInternal(CREDITUNIONBRANCHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreditUnionBranchId.
     * @param value value to set the CreditUnionBranchId
     */
    public void setCreditUnionBranchId(String value) {
        setAttributeInternal(CREDITUNIONBRANCHID, value);
    }

    /**
     * Gets the attribute value for UserTypeCode, using the alias name UserTypeCode.
     * @return the value of UserTypeCode
     */
    public String getUserTypeCode() {
        return (String) getAttributeInternal(USERTYPECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserTypeCode.
     * @param value value to set the UserTypeCode
     */
    public void setUserTypeCode(String value) {
        setAttributeInternal(USERTYPECODE, value);
    }

    /**
     * Gets the attribute value for UserRole, using the alias name UserRole.
     * @return the value of UserRole
     */
    public String getUserRole() {
        return (String) getAttributeInternal(USERROLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserRole.
     * @param value value to set the UserRole
     */
    public void setUserRole(String value) {
        setAttributeInternal(USERROLE, value);
    }

    /**
     * Gets the attribute value for UserSupervisor, using the alias name UserSupervisor.
     * @return the value of UserSupervisor
     */
    public String getUserSupervisor() {
        return (String) getAttributeInternal(USERSUPERVISOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserSupervisor.
     * @param value value to set the UserSupervisor
     */
    public void setUserSupervisor(String value) {
        setAttributeInternal(USERSUPERVISOR, value);
    }

    /**
     * Gets the attribute value for Email, using the alias name Email.
     * @return the value of Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Email.
     * @param value value to set the Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for MobilePhoneNumber, using the alias name MobilePhoneNumber.
     * @return the value of MobilePhoneNumber
     */
    public String getMobilePhoneNumber() {
        return (String) getAttributeInternal(MOBILEPHONENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for MobilePhoneNumber.
     * @param value value to set the MobilePhoneNumber
     */
    public void setMobilePhoneNumber(String value) {
        setAttributeInternal(MOBILEPHONENUMBER, value);
    }

    /**
     * Gets the attribute value for DateOfBirth, using the alias name DateOfBirth.
     * @return the value of DateOfBirth
     */
    public Timestamp getDateOfBirth() {
        return (Timestamp) getAttributeInternal(DATEOFBIRTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for DateOfBirth.
     * @param value value to set the DateOfBirth
     */
    public void setDateOfBirth(Timestamp value) {
        setAttributeInternal(DATEOFBIRTH, value);
    }

    /**
     * Gets the attribute value for Gender, using the alias name Gender.
     * @return the value of Gender
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gender.
     * @param value value to set the Gender
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for ObjectVersionId, using the alias name ObjectVersionId.
     * @return the value of ObjectVersionId
     */
    public Long getObjectVersionId() {
        return (Long) getAttributeInternal(OBJECTVERSIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ObjectVersionId.
     * @param value value to set the ObjectVersionId
     */
    public void setObjectVersionId(Long value) {
        setAttributeInternal(OBJECTVERSIONID, value);
    }

    /**
     * Gets the attribute value for LastApprovedBy, using the alias name LastApprovedBy.
     * @return the value of LastApprovedBy
     */
    public String getLastApprovedBy() {
        return (String) getAttributeInternal(LASTAPPROVEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastApprovedBy.
     * @param value value to set the LastApprovedBy
     */
    public void setLastApprovedBy(String value) {
        setAttributeInternal(LASTAPPROVEDBY, value);
    }

    /**
     * Gets the attribute value for LastApprovedDate, using the alias name LastApprovedDate.
     * @return the value of LastApprovedDate
     */
    public Timestamp getLastApprovedDate() {
        return (Timestamp) getAttributeInternal(LASTAPPROVEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastApprovedDate.
     * @param value value to set the LastApprovedDate
     */
    public void setLastApprovedDate(Timestamp value) {
        setAttributeInternal(LASTAPPROVEDDATE, value);
    }

    /**
     * Gets the attribute value for Password, using the alias name Password.
     * @return the value of Password
     */
    public String getPassword() {
        return (String) getAttributeInternal(PASSWORD);
    }

    /**
     * Sets <code>value</code> as the attribute value for Password.
     * @param value value to set the Password
     */
    public void setPassword(String value) {
        setAttributeInternal(PASSWORD, value);
    }

    /**
     * Gets the attribute value for UserName, using the alias name UserName.
     * @return the value of UserName
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserName.
     * @param value value to set the UserName
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for SecurityQustn, using the alias name SecurityQustn.
     * @return the value of SecurityQustn
     */
    public String getSecurityQustn() {
        return (String) getAttributeInternal(SECURITYQUSTN);
    }

    /**
     * Sets <code>value</code> as the attribute value for SecurityQustn.
     * @param value value to set the SecurityQustn
     */
    public void setSecurityQustn(String value) {
        setAttributeInternal(SECURITYQUSTN, value);
    }

    /**
     * Gets the attribute value for SecurityQustnAns, using the alias name SecurityQustnAns.
     * @return the value of SecurityQustnAns
     */
    public String getSecurityQustnAns() {
        return (String) getAttributeInternal(SECURITYQUSTNANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for SecurityQustnAns.
     * @param value value to set the SecurityQustnAns
     */
    public void setSecurityQustnAns(String value) {
        setAttributeInternal(SECURITYQUSTNANS, value);
    }

    /**
     * Gets the attribute value for FirstLoginFlag, using the alias name FirstLoginFlag.
     * @return the value of FirstLoginFlag
     */
    public String getFirstLoginFlag() {
        return (String) getAttributeInternal(FIRSTLOGINFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for FirstLoginFlag.
     * @param value value to set the FirstLoginFlag
     */
    public void setFirstLoginFlag(String value) {
        setAttributeInternal(FIRSTLOGINFLAG, value);
    }

    /**
     * Gets the attribute value for SecurityQustn1, using the alias name SecurityQustn1.
     * @return the value of SecurityQustn1
     */
    public String getSecurityQustn1() {
        return (String) getAttributeInternal(SECURITYQUSTN1);
    }

    /**
     * Sets <code>value</code> as the attribute value for SecurityQustn1.
     * @param value value to set the SecurityQustn1
     */
    public void setSecurityQustn1(String value) {
        setAttributeInternal(SECURITYQUSTN1, value);
    }

    /**
     * Gets the attribute value for SecurityQustnAns1, using the alias name SecurityQustnAns1.
     * @return the value of SecurityQustnAns1
     */
    public String getSecurityQustnAns1() {
        return (String) getAttributeInternal(SECURITYQUSTNANS1);
    }

    /**
     * Sets <code>value</code> as the attribute value for SecurityQustnAns1.
     * @param value value to set the SecurityQustnAns1
     */
    public void setSecurityQustnAns1(String value) {
        setAttributeInternal(SECURITYQUSTNANS1, value);
    }

    /**
     * Gets the attribute value for SecurityQustn2, using the alias name SecurityQustn2.
     * @return the value of SecurityQustn2
     */
    public String getSecurityQustn2() {
        return (String) getAttributeInternal(SECURITYQUSTN2);
    }

    /**
     * Sets <code>value</code> as the attribute value for SecurityQustn2.
     * @param value value to set the SecurityQustn2
     */
    public void setSecurityQustn2(String value) {
        setAttributeInternal(SECURITYQUSTN2, value);
    }

    /**
     * Gets the attribute value for SecurityQustnAns2, using the alias name SecurityQustnAns2.
     * @return the value of SecurityQustnAns2
     */
    public String getSecurityQustnAns2() {
        return (String) getAttributeInternal(SECURITYQUSTNANS2);
    }

    /**
     * Sets <code>value</code> as the attribute value for SecurityQustnAns2.
     * @param value value to set the SecurityQustnAns2
     */
    public void setSecurityQustnAns2(String value) {
        setAttributeInternal(SECURITYQUSTNANS2, value);
    }

    /**
     * Gets the attribute value for SecurityQustn3, using the alias name SecurityQustn3.
     * @return the value of SecurityQustn3
     */
    public String getSecurityQustn3() {
        return (String) getAttributeInternal(SECURITYQUSTN3);
    }

    /**
     * Sets <code>value</code> as the attribute value for SecurityQustn3.
     * @param value value to set the SecurityQustn3
     */
    public void setSecurityQustn3(String value) {
        setAttributeInternal(SECURITYQUSTN3, value);
    }

    /**
     * Gets the attribute value for SecurityQustnAns3, using the alias name SecurityQustnAns3.
     * @return the value of SecurityQustnAns3
     */
    public String getSecurityQustnAns3() {
        return (String) getAttributeInternal(SECURITYQUSTNANS3);
    }

    /**
     * Sets <code>value</code> as the attribute value for SecurityQustnAns3.
     * @param value value to set the SecurityQustnAns3
     */
    public void setSecurityQustnAns3(String value) {
        setAttributeInternal(SECURITYQUSTNANS3, value);
    }

    /**
     * Gets the attribute value for SecurityQustn4, using the alias name SecurityQustn4.
     * @return the value of SecurityQustn4
     */
    public String getSecurityQustn4() {
        return (String) getAttributeInternal(SECURITYQUSTN4);
    }

    /**
     * Sets <code>value</code> as the attribute value for SecurityQustn4.
     * @param value value to set the SecurityQustn4
     */
    public void setSecurityQustn4(String value) {
        setAttributeInternal(SECURITYQUSTN4, value);
    }

    /**
     * Gets the attribute value for SecurityQustnAns4, using the alias name SecurityQustnAns4.
     * @return the value of SecurityQustnAns4
     */
    public String getSecurityQustnAns4() {
        return (String) getAttributeInternal(SECURITYQUSTNANS4);
    }

    /**
     * Sets <code>value</code> as the attribute value for SecurityQustnAns4.
     * @param value value to set the SecurityQustnAns4
     */
    public void setSecurityQustnAns4(String value) {
        setAttributeInternal(SECURITYQUSTNANS4, value);
    }

    /**
     * Gets the attribute value for Active, using the alias name Active.
     * @return the value of Active
     */
    public String getActive() {
        return (String) getAttributeInternal(ACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Active.
     * @param value value to set the Active
     */
    public void setActive(String value) {
        setAttributeInternal(ACTIVE, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getCreditUnionBranchEO() {
        return (EntityImpl) getAttributeInternal(CREDITUNIONBRANCHEO);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setCreditUnionBranchEO(EntityImpl value) {
        setAttributeInternal(CREDITUNIONBRANCHEO, value);
    }


    /**
     * @param userId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Long userId) {
        return new Key(new Object[] { userId });
    }

    /**
     * Validation method for CreditUnionId.
     */
    public boolean validateCreditUnionId() {
        if((this.getUserTypeCode() != null) && ("CREDIT_UNION".equalsIgnoreCase(this.getUserTypeCode()))){
        return false;
        }else{
            return true;
        }
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        this.setUserId(new Long((new SequenceImpl("USER_ID_SEQ",getDBTransaction()).getSequenceNumber()).longValue()));
    }
    

}

