package com.linCu.model.view;

import com.linCu.model.view.common.CreditUnionVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 14 16:07:48 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CreditUnionVOImpl extends ViewObjectImpl implements CreditUnionVO {
    /**
     * This is the default constructor (do not remove).
     */
    public CreditUnionVOImpl() {
    }
    
    public void createCreditUnion(String user){
        CreditUnionVORowImpl row = (CreditUnionVORowImpl) this.createRow();
        long time = System.currentTimeMillis();
        java.sql.Timestamp timestamp = new java.sql.Timestamp(time);
        if(row != null){
        this.insertRow(row);
        this.setCurrentRow(row);
            row.setCreatedBy(user);
            row.setCreationDate(timestamp);
            row.setLastUpdatedBy(user);
            row.setLastUpdateDate(timestamp);
        }
    }
    
    public void updateCreditUnion(String user){
        CreditUnionVORowImpl row = (CreditUnionVORowImpl) this.getCurrentRow();
        if(row != null){
        this.executeQuery();
        row.setLastUpdatedBy(user);
        long time = System.currentTimeMillis();
        java.sql.Timestamp timestamp = new java.sql.Timestamp(time);
        row.setLastUpdateDate(timestamp);
        }
    }

}

