package com.linCu.model.view;

import com.linCu.model.view.common.CreditUnionBranchVORow;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 14 17:59:22 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CreditUnionBranchVORowImpl extends ViewRowImpl implements CreditUnionBranchVORow {


    public static final int ENTITY_CREDITUNIONBRANCHEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CreditUnionId,
        CreditUnionBranchId,
        CreditUnionBranchCode,
        CreditUnionBranchName,
        CreditUnionAddres1,
        CreditUnionAddres2,
        CreditUnionAddres3,
        CreditUnionAddres4,
        CreditUnionCity,
        CreditUnionCountry,
        CreditUnionPhone1,
        CreditUnionPhone2,
        CreditUnionEmailId,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        ObjectVersionId,
        LastApprovedBy,
        LastApprovedDate,
        Active,
        LincuUserInfoVO,
        CountryVA;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CREDITUNIONID = AttributesEnum.CreditUnionId.index();
    public static final int CREDITUNIONBRANCHID = AttributesEnum.CreditUnionBranchId.index();
    public static final int CREDITUNIONBRANCHCODE = AttributesEnum.CreditUnionBranchCode.index();
    public static final int CREDITUNIONBRANCHNAME = AttributesEnum.CreditUnionBranchName.index();
    public static final int CREDITUNIONADDRES1 = AttributesEnum.CreditUnionAddres1.index();
    public static final int CREDITUNIONADDRES2 = AttributesEnum.CreditUnionAddres2.index();
    public static final int CREDITUNIONADDRES3 = AttributesEnum.CreditUnionAddres3.index();
    public static final int CREDITUNIONADDRES4 = AttributesEnum.CreditUnionAddres4.index();
    public static final int CREDITUNIONCITY = AttributesEnum.CreditUnionCity.index();
    public static final int CREDITUNIONCOUNTRY = AttributesEnum.CreditUnionCountry.index();
    public static final int CREDITUNIONPHONE1 = AttributesEnum.CreditUnionPhone1.index();
    public static final int CREDITUNIONPHONE2 = AttributesEnum.CreditUnionPhone2.index();
    public static final int CREDITUNIONEMAILID = AttributesEnum.CreditUnionEmailId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int OBJECTVERSIONID = AttributesEnum.ObjectVersionId.index();
    public static final int LASTAPPROVEDBY = AttributesEnum.LastApprovedBy.index();
    public static final int LASTAPPROVEDDATE = AttributesEnum.LastApprovedDate.index();
    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int LINCUUSERINFOVO = AttributesEnum.LincuUserInfoVO.index();
    public static final int COUNTRYVA = AttributesEnum.CountryVA.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CreditUnionBranchVORowImpl() {
    }

    /**
     * Gets CreditUnionBranchEO entity object.
     * @return the CreditUnionBranchEO
     */
    public EntityImpl getCreditUnionBranchEO() {
        return (EntityImpl) getEntity(ENTITY_CREDITUNIONBRANCHEO);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_ID using the alias name CreditUnionId.
     * @return the CREDIT_UNION_ID
     */
    public String getCreditUnionId() {
        return (String) getAttributeInternal(CREDITUNIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_ID using the alias name CreditUnionId.
     * @param value value to set the CREDIT_UNION_ID
     */
    public void setCreditUnionId(String value) {
        setAttributeInternal(CREDITUNIONID, value);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_BRANCH_ID using the alias name CreditUnionBranchId.
     * @return the CREDIT_UNION_BRANCH_ID
     */
    public String getCreditUnionBranchId() {
        return (String) getAttributeInternal(CREDITUNIONBRANCHID);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_BRANCH_ID using the alias name CreditUnionBranchId.
     * @param value value to set the CREDIT_UNION_BRANCH_ID
     */
    public void setCreditUnionBranchId(String value) {
        setAttributeInternal(CREDITUNIONBRANCHID, value);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_BRANCH_CODE using the alias name CreditUnionBranchCode.
     * @return the CREDIT_UNION_BRANCH_CODE
     */
    public String getCreditUnionBranchCode() {
        return (String) getAttributeInternal(CREDITUNIONBRANCHCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_BRANCH_CODE using the alias name CreditUnionBranchCode.
     * @param value value to set the CREDIT_UNION_BRANCH_CODE
     */
    public void setCreditUnionBranchCode(String value) {
        setAttributeInternal(CREDITUNIONBRANCHCODE, value.toUpperCase());
    }

    /**
     * Gets the attribute value for CREDIT_UNION_BRANCH_NAME using the alias name CreditUnionBranchName.
     * @return the CREDIT_UNION_BRANCH_NAME
     */
    public String getCreditUnionBranchName() {
        return (String) getAttributeInternal(CREDITUNIONBRANCHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_BRANCH_NAME using the alias name CreditUnionBranchName.
     * @param value value to set the CREDIT_UNION_BRANCH_NAME
     */
    public void setCreditUnionBranchName(String value) {
        setAttributeInternal(CREDITUNIONBRANCHNAME, value);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_ADDRES_1 using the alias name CreditUnionAddres1.
     * @return the CREDIT_UNION_ADDRES_1
     */
    public String getCreditUnionAddres1() {
        return (String) getAttributeInternal(CREDITUNIONADDRES1);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_ADDRES_1 using the alias name CreditUnionAddres1.
     * @param value value to set the CREDIT_UNION_ADDRES_1
     */
    public void setCreditUnionAddres1(String value) {
        setAttributeInternal(CREDITUNIONADDRES1, value);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_ADDRES_2 using the alias name CreditUnionAddres2.
     * @return the CREDIT_UNION_ADDRES_2
     */
    public String getCreditUnionAddres2() {
        return (String) getAttributeInternal(CREDITUNIONADDRES2);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_ADDRES_2 using the alias name CreditUnionAddres2.
     * @param value value to set the CREDIT_UNION_ADDRES_2
     */
    public void setCreditUnionAddres2(String value) {
        setAttributeInternal(CREDITUNIONADDRES2, value);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_ADDRES_3 using the alias name CreditUnionAddres3.
     * @return the CREDIT_UNION_ADDRES_3
     */
    public String getCreditUnionAddres3() {
        return (String) getAttributeInternal(CREDITUNIONADDRES3);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_ADDRES_3 using the alias name CreditUnionAddres3.
     * @param value value to set the CREDIT_UNION_ADDRES_3
     */
    public void setCreditUnionAddres3(String value) {
        setAttributeInternal(CREDITUNIONADDRES3, value);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_ADDRES_4 using the alias name CreditUnionAddres4.
     * @return the CREDIT_UNION_ADDRES_4
     */
    public String getCreditUnionAddres4() {
        return (String) getAttributeInternal(CREDITUNIONADDRES4);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_ADDRES_4 using the alias name CreditUnionAddres4.
     * @param value value to set the CREDIT_UNION_ADDRES_4
     */
    public void setCreditUnionAddres4(String value) {
        setAttributeInternal(CREDITUNIONADDRES4, value);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_CITY using the alias name CreditUnionCity.
     * @return the CREDIT_UNION_CITY
     */
    public String getCreditUnionCity() {
        return (String) getAttributeInternal(CREDITUNIONCITY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_CITY using the alias name CreditUnionCity.
     * @param value value to set the CREDIT_UNION_CITY
     */
    public void setCreditUnionCity(String value) {
        setAttributeInternal(CREDITUNIONCITY, value);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_COUNTRY using the alias name CreditUnionCountry.
     * @return the CREDIT_UNION_COUNTRY
     */
    public String getCreditUnionCountry() {
        return (String) getAttributeInternal(CREDITUNIONCOUNTRY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_COUNTRY using the alias name CreditUnionCountry.
     * @param value value to set the CREDIT_UNION_COUNTRY
     */
    public void setCreditUnionCountry(String value) {
        setAttributeInternal(CREDITUNIONCOUNTRY, value);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_PHONE_1 using the alias name CreditUnionPhone1.
     * @return the CREDIT_UNION_PHONE_1
     */
    public String getCreditUnionPhone1() {
        return (String) getAttributeInternal(CREDITUNIONPHONE1);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_PHONE_1 using the alias name CreditUnionPhone1.
     * @param value value to set the CREDIT_UNION_PHONE_1
     */
    public void setCreditUnionPhone1(String value) {
        setAttributeInternal(CREDITUNIONPHONE1, value);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_PHONE_2 using the alias name CreditUnionPhone2.
     * @return the CREDIT_UNION_PHONE_2
     */
    public String getCreditUnionPhone2() {
        return (String) getAttributeInternal(CREDITUNIONPHONE2);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_PHONE_2 using the alias name CreditUnionPhone2.
     * @param value value to set the CREDIT_UNION_PHONE_2
     */
    public void setCreditUnionPhone2(String value) {
        setAttributeInternal(CREDITUNIONPHONE2, value);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_EMAIL_ID using the alias name CreditUnionEmailId.
     * @return the CREDIT_UNION_EMAIL_ID
     */
    public String getCreditUnionEmailId() {
        return (String) getAttributeInternal(CREDITUNIONEMAILID);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_EMAIL_ID using the alias name CreditUnionEmailId.
     * @param value value to set the CREDIT_UNION_EMAIL_ID
     */
    public void setCreditUnionEmailId(String value) {
        setAttributeInternal(CREDITUNIONEMAILID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId.
     * @return the OBJECT_VERSION_ID
     */
    public Long getObjectVersionId() {
        return (Long) getAttributeInternal(OBJECTVERSIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId.
     * @param value value to set the OBJECT_VERSION_ID
     */
    public void setObjectVersionId(Long value) {
        setAttributeInternal(OBJECTVERSIONID, value);
    }

    /**
     * Gets the attribute value for LAST_APPROVED_BY using the alias name LastApprovedBy.
     * @return the LAST_APPROVED_BY
     */
    public String getLastApprovedBy() {
        return (String) getAttributeInternal(LASTAPPROVEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_APPROVED_BY using the alias name LastApprovedBy.
     * @param value value to set the LAST_APPROVED_BY
     */
    public void setLastApprovedBy(String value) {
        setAttributeInternal(LASTAPPROVEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_APPROVED_DATE using the alias name LastApprovedDate.
     * @return the LAST_APPROVED_DATE
     */
    public Timestamp getLastApprovedDate() {
        return (Timestamp) getAttributeInternal(LASTAPPROVEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_APPROVED_DATE using the alias name LastApprovedDate.
     * @param value value to set the LAST_APPROVED_DATE
     */
    public void setLastApprovedDate(Timestamp value) {
        setAttributeInternal(LASTAPPROVEDDATE, value);
    }

    /**
     * Gets the attribute value for ACTIVE using the alias name Active.
     * @return the ACTIVE
     */
    public String getActive() {
        return (String) getAttributeInternal(ACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE using the alias name Active.
     * @param value value to set the ACTIVE
     */
    public void setActive(String value) {
        setAttributeInternal(ACTIVE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link LincuUserInfoVO.
     */
    public RowIterator getLincuUserInfoVO() {
        return (RowIterator) getAttributeInternal(LINCUUSERINFOVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryVA.
     */
    public RowSet getCountryVA() {
        return (RowSet) getAttributeInternal(COUNTRYVA);
    }
    public void closeBranch(){
        this.setActive("N");
    }
}

