package com.linCu.model.view;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 03 10:25:59 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LincuMemberCardVORowImpl extends ViewRowImpl {
    public static final int ENTITY_LINCUMEMBERCARDEO = 0;
    public static final int ENTITY_LINCUMEMBERINFOEO = 1;
    public static final int ENTITY_LINCUMEMBERKYCEO = 2;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AuthorizedBy,
        AuthorizedOn,
        CardId,
        CardReqType,
        CardStatus,
        CreatedBy,
        CreatedOn,
        CreditUnionId,
        MemberCardType,
        MemberId,
        SubmittedOn,
        BusinessPhoneExtn,
        BusinessPhoneNumber,
        CreatedBy1,
        CreationDate,
        CreditUnionBranchId,
        CreditUnionId1,
        DateOfBirth,
        Email,
        FaxNumber,
        FirstName,
        Gender,
        HomePhoneNumber,
        LastApprovedBy,
        LastApprovedDate,
        LastName,
        LastUpdateDate,
        LastUpdatedBy,
        MemberId1,
        MemberPrefix,
        MiddleName,
        MobilePhoneNumber,
        ObjectVersionId,
        TinOrSid,
        BirNo,
        BirthCountryCode,
        BirthCountryDesc,
        CitizenShipCountry1,
        CitizenShipCountry2,
        CitizenShipCountry3,
        CitizenShipCountry4,
        CreatedBy2,
        CreationDate1,
        CreditUnionBranchId1,
        CreditUnionId2,
        DocForeignTaxExempt,
        DpExpiryDate,
        DpIssueDate,
        DriverPermit,
        EducationCode,
        ElectorialId,
        EligibleForeignTax,
        Employer,
        EmployerAddress1,
        EmployerAddress2,
        EmployerCity,
        ForeignCitizenship,
        HomeOwnership,
        IncomeCode,
        LastApprovedBy1,
        LastApprovedDate1,
        LastUpdateDate1,
        LastUpdatedBy1,
        LocalTaxExempt,
        MailingAddrLine1,
        MailingAddrLine2,
        MailingAddrLine3,
        MailingAddrLine4,
        MailingCity,
        MailingCountryCode,
        MailingState,
        MailingZipCode,
        MaritalStatus,
        MemberId2,
        MonthlySalary,
        MotherMaidenName,
        Nationality,
        NoOfDependents,
        ObjectVersionId1,
        OccupationCode,
        PassportNo,
        PermanentAddrLine1,
        PermanentAddrLine2,
        PermanentAddrLine3,
        PermanentAddrLine4,
        PermanentCity,
        PermanentCountryCode,
        PermanentCountryDesc,
        PermanentState,
        PermanentZipCode,
        PowerOfAttorney,
        PpExpiryDate,
        PpIssueDate,
        ResidenceTin1,
        ResidenceTin2,
        ResidenceTin3,
        ResidenceTin4,
        ResidencyCode,
        ShareholderCode,
        StreetType,
        WorkPhone,
        Comments,
        CardTypeVA,
        LincuUnionsVA,
        MemberVA,
        ApplicationStatusVA,
        CountryVA,
        GenderVA,
        MaritalStatusVA,
        YesOrNoVA,
        HomeOwnershipVA,
        FCBShareholdingVA;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int AUTHORIZEDBY = AttributesEnum.AuthorizedBy.index();
    public static final int AUTHORIZEDON = AttributesEnum.AuthorizedOn.index();
    public static final int CARDID = AttributesEnum.CardId.index();
    public static final int CARDREQTYPE = AttributesEnum.CardReqType.index();
    public static final int CARDSTATUS = AttributesEnum.CardStatus.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDON = AttributesEnum.CreatedOn.index();
    public static final int CREDITUNIONID = AttributesEnum.CreditUnionId.index();
    public static final int MEMBERCARDTYPE = AttributesEnum.MemberCardType.index();
    public static final int MEMBERID = AttributesEnum.MemberId.index();
    public static final int SUBMITTEDON = AttributesEnum.SubmittedOn.index();
    public static final int BUSINESSPHONEEXTN = AttributesEnum.BusinessPhoneExtn.index();
    public static final int BUSINESSPHONENUMBER = AttributesEnum.BusinessPhoneNumber.index();
    public static final int CREATEDBY1 = AttributesEnum.CreatedBy1.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREDITUNIONBRANCHID = AttributesEnum.CreditUnionBranchId.index();
    public static final int CREDITUNIONID1 = AttributesEnum.CreditUnionId1.index();
    public static final int DATEOFBIRTH = AttributesEnum.DateOfBirth.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int FAXNUMBER = AttributesEnum.FaxNumber.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int HOMEPHONENUMBER = AttributesEnum.HomePhoneNumber.index();
    public static final int LASTAPPROVEDBY = AttributesEnum.LastApprovedBy.index();
    public static final int LASTAPPROVEDDATE = AttributesEnum.LastApprovedDate.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int MEMBERID1 = AttributesEnum.MemberId1.index();
    public static final int MEMBERPREFIX = AttributesEnum.MemberPrefix.index();
    public static final int MIDDLENAME = AttributesEnum.MiddleName.index();
    public static final int MOBILEPHONENUMBER = AttributesEnum.MobilePhoneNumber.index();
    public static final int OBJECTVERSIONID = AttributesEnum.ObjectVersionId.index();
    public static final int TINORSID = AttributesEnum.TinOrSid.index();
    public static final int BIRNO = AttributesEnum.BirNo.index();
    public static final int BIRTHCOUNTRYCODE = AttributesEnum.BirthCountryCode.index();
    public static final int BIRTHCOUNTRYDESC = AttributesEnum.BirthCountryDesc.index();
    public static final int CITIZENSHIPCOUNTRY1 = AttributesEnum.CitizenShipCountry1.index();
    public static final int CITIZENSHIPCOUNTRY2 = AttributesEnum.CitizenShipCountry2.index();
    public static final int CITIZENSHIPCOUNTRY3 = AttributesEnum.CitizenShipCountry3.index();
    public static final int CITIZENSHIPCOUNTRY4 = AttributesEnum.CitizenShipCountry4.index();
    public static final int CREATEDBY2 = AttributesEnum.CreatedBy2.index();
    public static final int CREATIONDATE1 = AttributesEnum.CreationDate1.index();
    public static final int CREDITUNIONBRANCHID1 = AttributesEnum.CreditUnionBranchId1.index();
    public static final int CREDITUNIONID2 = AttributesEnum.CreditUnionId2.index();
    public static final int DOCFOREIGNTAXEXEMPT = AttributesEnum.DocForeignTaxExempt.index();
    public static final int DPEXPIRYDATE = AttributesEnum.DpExpiryDate.index();
    public static final int DPISSUEDATE = AttributesEnum.DpIssueDate.index();
    public static final int DRIVERPERMIT = AttributesEnum.DriverPermit.index();
    public static final int EDUCATIONCODE = AttributesEnum.EducationCode.index();
    public static final int ELECTORIALID = AttributesEnum.ElectorialId.index();
    public static final int ELIGIBLEFOREIGNTAX = AttributesEnum.EligibleForeignTax.index();
    public static final int EMPLOYER = AttributesEnum.Employer.index();
    public static final int EMPLOYERADDRESS1 = AttributesEnum.EmployerAddress1.index();
    public static final int EMPLOYERADDRESS2 = AttributesEnum.EmployerAddress2.index();
    public static final int EMPLOYERCITY = AttributesEnum.EmployerCity.index();
    public static final int FOREIGNCITIZENSHIP = AttributesEnum.ForeignCitizenship.index();
    public static final int HOMEOWNERSHIP = AttributesEnum.HomeOwnership.index();
    public static final int INCOMECODE = AttributesEnum.IncomeCode.index();
    public static final int LASTAPPROVEDBY1 = AttributesEnum.LastApprovedBy1.index();
    public static final int LASTAPPROVEDDATE1 = AttributesEnum.LastApprovedDate1.index();
    public static final int LASTUPDATEDATE1 = AttributesEnum.LastUpdateDate1.index();
    public static final int LASTUPDATEDBY1 = AttributesEnum.LastUpdatedBy1.index();
    public static final int LOCALTAXEXEMPT = AttributesEnum.LocalTaxExempt.index();
    public static final int MAILINGADDRLINE1 = AttributesEnum.MailingAddrLine1.index();
    public static final int MAILINGADDRLINE2 = AttributesEnum.MailingAddrLine2.index();
    public static final int MAILINGADDRLINE3 = AttributesEnum.MailingAddrLine3.index();
    public static final int MAILINGADDRLINE4 = AttributesEnum.MailingAddrLine4.index();
    public static final int MAILINGCITY = AttributesEnum.MailingCity.index();
    public static final int MAILINGCOUNTRYCODE = AttributesEnum.MailingCountryCode.index();
    public static final int MAILINGSTATE = AttributesEnum.MailingState.index();
    public static final int MAILINGZIPCODE = AttributesEnum.MailingZipCode.index();
    public static final int MARITALSTATUS = AttributesEnum.MaritalStatus.index();
    public static final int MEMBERID2 = AttributesEnum.MemberId2.index();
    public static final int MONTHLYSALARY = AttributesEnum.MonthlySalary.index();
    public static final int MOTHERMAIDENNAME = AttributesEnum.MotherMaidenName.index();
    public static final int NATIONALITY = AttributesEnum.Nationality.index();
    public static final int NOOFDEPENDENTS = AttributesEnum.NoOfDependents.index();
    public static final int OBJECTVERSIONID1 = AttributesEnum.ObjectVersionId1.index();
    public static final int OCCUPATIONCODE = AttributesEnum.OccupationCode.index();
    public static final int PASSPORTNO = AttributesEnum.PassportNo.index();
    public static final int PERMANENTADDRLINE1 = AttributesEnum.PermanentAddrLine1.index();
    public static final int PERMANENTADDRLINE2 = AttributesEnum.PermanentAddrLine2.index();
    public static final int PERMANENTADDRLINE3 = AttributesEnum.PermanentAddrLine3.index();
    public static final int PERMANENTADDRLINE4 = AttributesEnum.PermanentAddrLine4.index();
    public static final int PERMANENTCITY = AttributesEnum.PermanentCity.index();
    public static final int PERMANENTCOUNTRYCODE = AttributesEnum.PermanentCountryCode.index();
    public static final int PERMANENTCOUNTRYDESC = AttributesEnum.PermanentCountryDesc.index();
    public static final int PERMANENTSTATE = AttributesEnum.PermanentState.index();
    public static final int PERMANENTZIPCODE = AttributesEnum.PermanentZipCode.index();
    public static final int POWEROFATTORNEY = AttributesEnum.PowerOfAttorney.index();
    public static final int PPEXPIRYDATE = AttributesEnum.PpExpiryDate.index();
    public static final int PPISSUEDATE = AttributesEnum.PpIssueDate.index();
    public static final int RESIDENCETIN1 = AttributesEnum.ResidenceTin1.index();
    public static final int RESIDENCETIN2 = AttributesEnum.ResidenceTin2.index();
    public static final int RESIDENCETIN3 = AttributesEnum.ResidenceTin3.index();
    public static final int RESIDENCETIN4 = AttributesEnum.ResidenceTin4.index();
    public static final int RESIDENCYCODE = AttributesEnum.ResidencyCode.index();
    public static final int SHAREHOLDERCODE = AttributesEnum.ShareholderCode.index();
    public static final int STREETTYPE = AttributesEnum.StreetType.index();
    public static final int WORKPHONE = AttributesEnum.WorkPhone.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int CARDTYPEVA = AttributesEnum.CardTypeVA.index();
    public static final int LINCUUNIONSVA = AttributesEnum.LincuUnionsVA.index();
    public static final int MEMBERVA = AttributesEnum.MemberVA.index();
    public static final int APPLICATIONSTATUSVA = AttributesEnum.ApplicationStatusVA.index();
    public static final int COUNTRYVA = AttributesEnum.CountryVA.index();
    public static final int GENDERVA = AttributesEnum.GenderVA.index();
    public static final int MARITALSTATUSVA = AttributesEnum.MaritalStatusVA.index();
    public static final int YESORNOVA = AttributesEnum.YesOrNoVA.index();
    public static final int HOMEOWNERSHIPVA = AttributesEnum.HomeOwnershipVA.index();
    public static final int FCBSHAREHOLDINGVA = AttributesEnum.FCBShareholdingVA.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LincuMemberCardVORowImpl() {
    }

    /**
     * Gets LincuMemberCardEO entity object.
     * @return the LincuMemberCardEO
     */
    public EntityImpl getLincuMemberCardEO() {
        return (EntityImpl) getEntity(ENTITY_LINCUMEMBERCARDEO);
    }

    /**
     * Gets LincuMemberInfoEO entity object.
     * @return the LincuMemberInfoEO
     */
    public EntityImpl getLincuMemberInfoEO() {
        return (EntityImpl) getEntity(ENTITY_LINCUMEMBERINFOEO);
    }

    /**
     * Gets LincuMemberKycEO entity object.
     * @return the LincuMemberKycEO
     */
    public EntityImpl getLincuMemberKycEO() {
        return (EntityImpl) getEntity(ENTITY_LINCUMEMBERKYCEO);
    }

    /**
     * Gets the attribute value for AUTHORIZED_BY using the alias name AuthorizedBy.
     * @return the AUTHORIZED_BY
     */
    public String getAuthorizedBy() {
        return (String) getAttributeInternal(AUTHORIZEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for AUTHORIZED_BY using the alias name AuthorizedBy.
     * @param value value to set the AUTHORIZED_BY
     */
    public void setAuthorizedBy(String value) {
        setAttributeInternal(AUTHORIZEDBY, value);
    }

    /**
     * Gets the attribute value for AUTHORIZED_ON using the alias name AuthorizedOn.
     * @return the AUTHORIZED_ON
     */
    public Timestamp getAuthorizedOn() {
        return (Timestamp) getAttributeInternal(AUTHORIZEDON);
    }

    /**
     * Sets <code>value</code> as attribute value for AUTHORIZED_ON using the alias name AuthorizedOn.
     * @param value value to set the AUTHORIZED_ON
     */
    public void setAuthorizedOn(Timestamp value) {
        setAttributeInternal(AUTHORIZEDON, value);
    }

    /**
     * Gets the attribute value for CARD_ID using the alias name CardId.
     * @return the CARD_ID
     */
    public BigDecimal getCardId() {
        return (BigDecimal) getAttributeInternal(CARDID);
    }

    /**
     * Sets <code>value</code> as attribute value for CARD_ID using the alias name CardId.
     * @param value value to set the CARD_ID
     */
    public void setCardId(BigDecimal value) {
        setAttributeInternal(CARDID, value);
    }

    /**
     * Gets the attribute value for CARD_REQ_TYPE using the alias name CardReqType.
     * @return the CARD_REQ_TYPE
     */
    public String getCardReqType() {
        return (String) getAttributeInternal(CARDREQTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for CARD_REQ_TYPE using the alias name CardReqType.
     * @param value value to set the CARD_REQ_TYPE
     */
    public void setCardReqType(String value) {
        setAttributeInternal(CARDREQTYPE, value);
    }

    /**
     * Gets the attribute value for CARD_STATUS using the alias name CardStatus.
     * @return the CARD_STATUS
     */
    public String getCardStatus() {
        return (String) getAttributeInternal(CARDSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for CARD_STATUS using the alias name CardStatus.
     * @param value value to set the CARD_STATUS
     */
    public void setCardStatus(String value) {
        setAttributeInternal(CARDSTATUS, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_ON using the alias name CreatedOn.
     * @return the CREATED_ON
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) getAttributeInternal(CREATEDON);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_ON using the alias name CreatedOn.
     * @param value value to set the CREATED_ON
     */
    public void setCreatedOn(Timestamp value) {
        setAttributeInternal(CREATEDON, value);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_ID using the alias name CreditUnionId.
     * @return the CREDIT_UNION_ID
     */
    public String getCreditUnionId() {
        return (String) getAttributeInternal(CREDITUNIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_ID using the alias name CreditUnionId.
     * @param value value to set the CREDIT_UNION_ID
     */
    public void setCreditUnionId(String value) {
        setAttributeInternal(CREDITUNIONID, value);
    }

    /**
     * Gets the attribute value for MEMBER_CARD_TYPE using the alias name MemberCardType.
     * @return the MEMBER_CARD_TYPE
     */
    public String getMemberCardType() {
        return (String) getAttributeInternal(MEMBERCARDTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for MEMBER_CARD_TYPE using the alias name MemberCardType.
     * @param value value to set the MEMBER_CARD_TYPE
     */
    public void setMemberCardType(String value) {
        setAttributeInternal(MEMBERCARDTYPE, value);
    }

    /**
     * Gets the attribute value for MEMBER_ID using the alias name MemberId.
     * @return the MEMBER_ID
     */
    public String getMemberId() {
        return (String) getAttributeInternal(MEMBERID);
    }

    /**
     * Sets <code>value</code> as attribute value for MEMBER_ID using the alias name MemberId.
     * @param value value to set the MEMBER_ID
     */
    public void setMemberId(String value) {
        setAttributeInternal(MEMBERID, value);
    }

    /**
     * Gets the attribute value for SUBMITTED_ON using the alias name SubmittedOn.
     * @return the SUBMITTED_ON
     */
    public Timestamp getSubmittedOn() {
        return (Timestamp) getAttributeInternal(SUBMITTEDON);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMITTED_ON using the alias name SubmittedOn.
     * @param value value to set the SUBMITTED_ON
     */
    public void setSubmittedOn(Timestamp value) {
        setAttributeInternal(SUBMITTEDON, value);
    }

    /**
     * Gets the attribute value for BUSINESS_PHONE_EXTN using the alias name BusinessPhoneExtn.
     * @return the BUSINESS_PHONE_EXTN
     */
    public String getBusinessPhoneExtn() {
        return (String) getAttributeInternal(BUSINESSPHONEEXTN);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_PHONE_EXTN using the alias name BusinessPhoneExtn.
     * @param value value to set the BUSINESS_PHONE_EXTN
     */
    public void setBusinessPhoneExtn(String value) {
        setAttributeInternal(BUSINESSPHONEEXTN, value);
    }

    /**
     * Gets the attribute value for BUSINESS_PHONE_NUMBER using the alias name BusinessPhoneNumber.
     * @return the BUSINESS_PHONE_NUMBER
     */
    public String getBusinessPhoneNumber() {
        return (String) getAttributeInternal(BUSINESSPHONENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_PHONE_NUMBER using the alias name BusinessPhoneNumber.
     * @param value value to set the BUSINESS_PHONE_NUMBER
     */
    public void setBusinessPhoneNumber(String value) {
        setAttributeInternal(BUSINESSPHONENUMBER, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy1.
     * @return the CREATED_BY
     */
    public String getCreatedBy1() {
        return (String) getAttributeInternal(CREATEDBY1);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy1.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy1(String value) {
        setAttributeInternal(CREATEDBY1, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_BRANCH_ID using the alias name CreditUnionBranchId.
     * @return the CREDIT_UNION_BRANCH_ID
     */
    public String getCreditUnionBranchId() {
        return (String) getAttributeInternal(CREDITUNIONBRANCHID);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_BRANCH_ID using the alias name CreditUnionBranchId.
     * @param value value to set the CREDIT_UNION_BRANCH_ID
     */
    public void setCreditUnionBranchId(String value) {
        setAttributeInternal(CREDITUNIONBRANCHID, value);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_ID using the alias name CreditUnionId1.
     * @return the CREDIT_UNION_ID
     */
    public String getCreditUnionId1() {
        return (String) getAttributeInternal(CREDITUNIONID1);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_ID using the alias name CreditUnionId1.
     * @param value value to set the CREDIT_UNION_ID
     */
    public void setCreditUnionId1(String value) {
        setAttributeInternal(CREDITUNIONID1, value);
    }

    /**
     * Gets the attribute value for DATE_OF_BIRTH using the alias name DateOfBirth.
     * @return the DATE_OF_BIRTH
     */
    public Timestamp getDateOfBirth() {
        return (Timestamp) getAttributeInternal(DATEOFBIRTH);
    }

    /**
     * Sets <code>value</code> as attribute value for DATE_OF_BIRTH using the alias name DateOfBirth.
     * @param value value to set the DATE_OF_BIRTH
     */
    public void setDateOfBirth(Timestamp value) {
        setAttributeInternal(DATEOFBIRTH, value);
    }

    /**
     * Gets the attribute value for EMAIL using the alias name Email.
     * @return the EMAIL
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL using the alias name Email.
     * @param value value to set the EMAIL
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for FAX_NUMBER using the alias name FaxNumber.
     * @return the FAX_NUMBER
     */
    public String getFaxNumber() {
        return (String) getAttributeInternal(FAXNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for FAX_NUMBER using the alias name FaxNumber.
     * @param value value to set the FAX_NUMBER
     */
    public void setFaxNumber(String value) {
        setAttributeInternal(FAXNUMBER, value);
    }

    /**
     * Gets the attribute value for FIRST_NAME using the alias name FirstName.
     * @return the FIRST_NAME
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName.
     * @param value value to set the FIRST_NAME
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for GENDER using the alias name Gender.
     * @return the GENDER
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as attribute value for GENDER using the alias name Gender.
     * @param value value to set the GENDER
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for HOME_PHONE_NUMBER using the alias name HomePhoneNumber.
     * @return the HOME_PHONE_NUMBER
     */
    public String getHomePhoneNumber() {
        return (String) getAttributeInternal(HOMEPHONENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for HOME_PHONE_NUMBER using the alias name HomePhoneNumber.
     * @param value value to set the HOME_PHONE_NUMBER
     */
    public void setHomePhoneNumber(String value) {
        setAttributeInternal(HOMEPHONENUMBER, value);
    }

    /**
     * Gets the attribute value for LAST_APPROVED_BY using the alias name LastApprovedBy.
     * @return the LAST_APPROVED_BY
     */
    public String getLastApprovedBy() {
        return (String) getAttributeInternal(LASTAPPROVEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_APPROVED_BY using the alias name LastApprovedBy.
     * @param value value to set the LAST_APPROVED_BY
     */
    public void setLastApprovedBy(String value) {
        setAttributeInternal(LASTAPPROVEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_APPROVED_DATE using the alias name LastApprovedDate.
     * @return the LAST_APPROVED_DATE
     */
    public Timestamp getLastApprovedDate() {
        return (Timestamp) getAttributeInternal(LASTAPPROVEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_APPROVED_DATE using the alias name LastApprovedDate.
     * @param value value to set the LAST_APPROVED_DATE
     */
    public void setLastApprovedDate(Timestamp value) {
        setAttributeInternal(LASTAPPROVEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_NAME using the alias name LastName.
     * @return the LAST_NAME
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName.
     * @param value value to set the LAST_NAME
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for MEMBER_ID using the alias name MemberId1.
     * @return the MEMBER_ID
     */
    public String getMemberId1() {
        return (String) getAttributeInternal(MEMBERID1);
    }

    /**
     * Sets <code>value</code> as attribute value for MEMBER_ID using the alias name MemberId1.
     * @param value value to set the MEMBER_ID
     */
    public void setMemberId1(String value) {
        setAttributeInternal(MEMBERID1, value);
    }

    /**
     * Gets the attribute value for MEMBER_PREFIX using the alias name MemberPrefix.
     * @return the MEMBER_PREFIX
     */
    public String getMemberPrefix() {
        return (String) getAttributeInternal(MEMBERPREFIX);
    }

    /**
     * Sets <code>value</code> as attribute value for MEMBER_PREFIX using the alias name MemberPrefix.
     * @param value value to set the MEMBER_PREFIX
     */
    public void setMemberPrefix(String value) {
        setAttributeInternal(MEMBERPREFIX, value);
    }

    /**
     * Gets the attribute value for MIDDLE_NAME using the alias name MiddleName.
     * @return the MIDDLE_NAME
     */
    public String getMiddleName() {
        return (String) getAttributeInternal(MIDDLENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for MIDDLE_NAME using the alias name MiddleName.
     * @param value value to set the MIDDLE_NAME
     */
    public void setMiddleName(String value) {
        setAttributeInternal(MIDDLENAME, value);
    }

    /**
     * Gets the attribute value for MOBILE_PHONE_NUMBER using the alias name MobilePhoneNumber.
     * @return the MOBILE_PHONE_NUMBER
     */
    public String getMobilePhoneNumber() {
        return (String) getAttributeInternal(MOBILEPHONENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for MOBILE_PHONE_NUMBER using the alias name MobilePhoneNumber.
     * @param value value to set the MOBILE_PHONE_NUMBER
     */
    public void setMobilePhoneNumber(String value) {
        setAttributeInternal(MOBILEPHONENUMBER, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId.
     * @return the OBJECT_VERSION_ID
     */
    public Long getObjectVersionId() {
        return (Long) getAttributeInternal(OBJECTVERSIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId.
     * @param value value to set the OBJECT_VERSION_ID
     */
    public void setObjectVersionId(Long value) {
        setAttributeInternal(OBJECTVERSIONID, value);
    }

    /**
     * Gets the attribute value for TIN_OR_SID using the alias name TinOrSid.
     * @return the TIN_OR_SID
     */
    public String getTinOrSid() {
        return (String) getAttributeInternal(TINORSID);
    }

    /**
     * Sets <code>value</code> as attribute value for TIN_OR_SID using the alias name TinOrSid.
     * @param value value to set the TIN_OR_SID
     */
    public void setTinOrSid(String value) {
        setAttributeInternal(TINORSID, value);
    }

    /**
     * Gets the attribute value for BIR_NO using the alias name BirNo.
     * @return the BIR_NO
     */
    public String getBirNo() {
        return (String) getAttributeInternal(BIRNO);
    }

    /**
     * Sets <code>value</code> as attribute value for BIR_NO using the alias name BirNo.
     * @param value value to set the BIR_NO
     */
    public void setBirNo(String value) {
        setAttributeInternal(BIRNO, value);
    }

    /**
     * Gets the attribute value for BIRTH_COUNTRY_CODE using the alias name BirthCountryCode.
     * @return the BIRTH_COUNTRY_CODE
     */
    public String getBirthCountryCode() {
        return (String) getAttributeInternal(BIRTHCOUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for BIRTH_COUNTRY_CODE using the alias name BirthCountryCode.
     * @param value value to set the BIRTH_COUNTRY_CODE
     */
    public void setBirthCountryCode(String value) {
        setAttributeInternal(BIRTHCOUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for BIRTH_COUNTRY_DESC using the alias name BirthCountryDesc.
     * @return the BIRTH_COUNTRY_DESC
     */
    public String getBirthCountryDesc() {
        return (String) getAttributeInternal(BIRTHCOUNTRYDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for BIRTH_COUNTRY_DESC using the alias name BirthCountryDesc.
     * @param value value to set the BIRTH_COUNTRY_DESC
     */
    public void setBirthCountryDesc(String value) {
        setAttributeInternal(BIRTHCOUNTRYDESC, value);
    }

    /**
     * Gets the attribute value for CITIZEN_SHIP_COUNTRY1 using the alias name CitizenShipCountry1.
     * @return the CITIZEN_SHIP_COUNTRY1
     */
    public String getCitizenShipCountry1() {
        return (String) getAttributeInternal(CITIZENSHIPCOUNTRY1);
    }

    /**
     * Sets <code>value</code> as attribute value for CITIZEN_SHIP_COUNTRY1 using the alias name CitizenShipCountry1.
     * @param value value to set the CITIZEN_SHIP_COUNTRY1
     */
    public void setCitizenShipCountry1(String value) {
        setAttributeInternal(CITIZENSHIPCOUNTRY1, value);
    }

    /**
     * Gets the attribute value for CITIZEN_SHIP_COUNTRY2 using the alias name CitizenShipCountry2.
     * @return the CITIZEN_SHIP_COUNTRY2
     */
    public String getCitizenShipCountry2() {
        return (String) getAttributeInternal(CITIZENSHIPCOUNTRY2);
    }

    /**
     * Sets <code>value</code> as attribute value for CITIZEN_SHIP_COUNTRY2 using the alias name CitizenShipCountry2.
     * @param value value to set the CITIZEN_SHIP_COUNTRY2
     */
    public void setCitizenShipCountry2(String value) {
        setAttributeInternal(CITIZENSHIPCOUNTRY2, value);
    }

    /**
     * Gets the attribute value for CITIZEN_SHIP_COUNTRY3 using the alias name CitizenShipCountry3.
     * @return the CITIZEN_SHIP_COUNTRY3
     */
    public String getCitizenShipCountry3() {
        return (String) getAttributeInternal(CITIZENSHIPCOUNTRY3);
    }

    /**
     * Sets <code>value</code> as attribute value for CITIZEN_SHIP_COUNTRY3 using the alias name CitizenShipCountry3.
     * @param value value to set the CITIZEN_SHIP_COUNTRY3
     */
    public void setCitizenShipCountry3(String value) {
        setAttributeInternal(CITIZENSHIPCOUNTRY3, value);
    }

    /**
     * Gets the attribute value for CITIZEN_SHIP_COUNTRY4 using the alias name CitizenShipCountry4.
     * @return the CITIZEN_SHIP_COUNTRY4
     */
    public String getCitizenShipCountry4() {
        return (String) getAttributeInternal(CITIZENSHIPCOUNTRY4);
    }

    /**
     * Sets <code>value</code> as attribute value for CITIZEN_SHIP_COUNTRY4 using the alias name CitizenShipCountry4.
     * @param value value to set the CITIZEN_SHIP_COUNTRY4
     */
    public void setCitizenShipCountry4(String value) {
        setAttributeInternal(CITIZENSHIPCOUNTRY4, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy2.
     * @return the CREATED_BY
     */
    public String getCreatedBy2() {
        return (String) getAttributeInternal(CREATEDBY2);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy2.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy2(String value) {
        setAttributeInternal(CREATEDBY2, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate1.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate1() {
        return (Timestamp) getAttributeInternal(CREATIONDATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate1.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate1(Timestamp value) {
        setAttributeInternal(CREATIONDATE1, value);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_BRANCH_ID using the alias name CreditUnionBranchId1.
     * @return the CREDIT_UNION_BRANCH_ID
     */
    public String getCreditUnionBranchId1() {
        return (String) getAttributeInternal(CREDITUNIONBRANCHID1);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_BRANCH_ID using the alias name CreditUnionBranchId1.
     * @param value value to set the CREDIT_UNION_BRANCH_ID
     */
    public void setCreditUnionBranchId1(String value) {
        setAttributeInternal(CREDITUNIONBRANCHID1, value);
    }

    /**
     * Gets the attribute value for CREDIT_UNION_ID using the alias name CreditUnionId2.
     * @return the CREDIT_UNION_ID
     */
    public String getCreditUnionId2() {
        return (String) getAttributeInternal(CREDITUNIONID2);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_UNION_ID using the alias name CreditUnionId2.
     * @param value value to set the CREDIT_UNION_ID
     */
    public void setCreditUnionId2(String value) {
        setAttributeInternal(CREDITUNIONID2, value);
    }

    /**
     * Gets the attribute value for DOC_FOREIGN_TAX_EXEMPT using the alias name DocForeignTaxExempt.
     * @return the DOC_FOREIGN_TAX_EXEMPT
     */
    public String getDocForeignTaxExempt() {
        return (String) getAttributeInternal(DOCFOREIGNTAXEXEMPT);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_FOREIGN_TAX_EXEMPT using the alias name DocForeignTaxExempt.
     * @param value value to set the DOC_FOREIGN_TAX_EXEMPT
     */
    public void setDocForeignTaxExempt(String value) {
        setAttributeInternal(DOCFOREIGNTAXEXEMPT, value);
    }

    /**
     * Gets the attribute value for DP_EXPIRY_DATE using the alias name DpExpiryDate.
     * @return the DP_EXPIRY_DATE
     */
    public Timestamp getDpExpiryDate() {
        return (Timestamp) getAttributeInternal(DPEXPIRYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DP_EXPIRY_DATE using the alias name DpExpiryDate.
     * @param value value to set the DP_EXPIRY_DATE
     */
    public void setDpExpiryDate(Timestamp value) {
        setAttributeInternal(DPEXPIRYDATE, value);
    }

    /**
     * Gets the attribute value for DP_ISSUE_DATE using the alias name DpIssueDate.
     * @return the DP_ISSUE_DATE
     */
    public Timestamp getDpIssueDate() {
        return (Timestamp) getAttributeInternal(DPISSUEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DP_ISSUE_DATE using the alias name DpIssueDate.
     * @param value value to set the DP_ISSUE_DATE
     */
    public void setDpIssueDate(Timestamp value) {
        setAttributeInternal(DPISSUEDATE, value);
    }

    /**
     * Gets the attribute value for DRIVER_PERMIT using the alias name DriverPermit.
     * @return the DRIVER_PERMIT
     */
    public String getDriverPermit() {
        return (String) getAttributeInternal(DRIVERPERMIT);
    }

    /**
     * Sets <code>value</code> as attribute value for DRIVER_PERMIT using the alias name DriverPermit.
     * @param value value to set the DRIVER_PERMIT
     */
    public void setDriverPermit(String value) {
        setAttributeInternal(DRIVERPERMIT, value);
    }

    /**
     * Gets the attribute value for EDUCATION_CODE using the alias name EducationCode.
     * @return the EDUCATION_CODE
     */
    public String getEducationCode() {
        return (String) getAttributeInternal(EDUCATIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for EDUCATION_CODE using the alias name EducationCode.
     * @param value value to set the EDUCATION_CODE
     */
    public void setEducationCode(String value) {
        setAttributeInternal(EDUCATIONCODE, value);
    }

    /**
     * Gets the attribute value for ELECTORIAL_ID using the alias name ElectorialId.
     * @return the ELECTORIAL_ID
     */
    public String getElectorialId() {
        return (String) getAttributeInternal(ELECTORIALID);
    }

    /**
     * Sets <code>value</code> as attribute value for ELECTORIAL_ID using the alias name ElectorialId.
     * @param value value to set the ELECTORIAL_ID
     */
    public void setElectorialId(String value) {
        setAttributeInternal(ELECTORIALID, value);
    }

    /**
     * Gets the attribute value for ELIGIBLE_FOREIGN_TAX using the alias name EligibleForeignTax.
     * @return the ELIGIBLE_FOREIGN_TAX
     */
    public String getEligibleForeignTax() {
        return (String) getAttributeInternal(ELIGIBLEFOREIGNTAX);
    }

    /**
     * Sets <code>value</code> as attribute value for ELIGIBLE_FOREIGN_TAX using the alias name EligibleForeignTax.
     * @param value value to set the ELIGIBLE_FOREIGN_TAX
     */
    public void setEligibleForeignTax(String value) {
        setAttributeInternal(ELIGIBLEFOREIGNTAX, value);
    }

    /**
     * Gets the attribute value for EMPLOYER using the alias name Employer.
     * @return the EMPLOYER
     */
    public String getEmployer() {
        return (String) getAttributeInternal(EMPLOYER);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYER using the alias name Employer.
     * @param value value to set the EMPLOYER
     */
    public void setEmployer(String value) {
        setAttributeInternal(EMPLOYER, value);
    }

    /**
     * Gets the attribute value for EMPLOYER_ADDRESS1 using the alias name EmployerAddress1.
     * @return the EMPLOYER_ADDRESS1
     */
    public String getEmployerAddress1() {
        return (String) getAttributeInternal(EMPLOYERADDRESS1);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYER_ADDRESS1 using the alias name EmployerAddress1.
     * @param value value to set the EMPLOYER_ADDRESS1
     */
    public void setEmployerAddress1(String value) {
        setAttributeInternal(EMPLOYERADDRESS1, value);
    }

    /**
     * Gets the attribute value for EMPLOYER_ADDRESS2 using the alias name EmployerAddress2.
     * @return the EMPLOYER_ADDRESS2
     */
    public String getEmployerAddress2() {
        return (String) getAttributeInternal(EMPLOYERADDRESS2);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYER_ADDRESS2 using the alias name EmployerAddress2.
     * @param value value to set the EMPLOYER_ADDRESS2
     */
    public void setEmployerAddress2(String value) {
        setAttributeInternal(EMPLOYERADDRESS2, value);
    }

    /**
     * Gets the attribute value for EMPLOYER_CITY using the alias name EmployerCity.
     * @return the EMPLOYER_CITY
     */
    public String getEmployerCity() {
        return (String) getAttributeInternal(EMPLOYERCITY);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYER_CITY using the alias name EmployerCity.
     * @param value value to set the EMPLOYER_CITY
     */
    public void setEmployerCity(String value) {
        setAttributeInternal(EMPLOYERCITY, value);
    }

    /**
     * Gets the attribute value for FOREIGN_CITIZENSHIP using the alias name ForeignCitizenship.
     * @return the FOREIGN_CITIZENSHIP
     */
    public String getForeignCitizenship() {
        return (String) getAttributeInternal(FOREIGNCITIZENSHIP);
    }

    /**
     * Sets <code>value</code> as attribute value for FOREIGN_CITIZENSHIP using the alias name ForeignCitizenship.
     * @param value value to set the FOREIGN_CITIZENSHIP
     */
    public void setForeignCitizenship(String value) {
        setAttributeInternal(FOREIGNCITIZENSHIP, value);
    }

    /**
     * Gets the attribute value for HOME_OWNERSHIP using the alias name HomeOwnership.
     * @return the HOME_OWNERSHIP
     */
    public String getHomeOwnership() {
        return (String) getAttributeInternal(HOMEOWNERSHIP);
    }

    /**
     * Sets <code>value</code> as attribute value for HOME_OWNERSHIP using the alias name HomeOwnership.
     * @param value value to set the HOME_OWNERSHIP
     */
    public void setHomeOwnership(String value) {
        setAttributeInternal(HOMEOWNERSHIP, value);
    }

    /**
     * Gets the attribute value for INCOME_CODE using the alias name IncomeCode.
     * @return the INCOME_CODE
     */
    public String getIncomeCode() {
        return (String) getAttributeInternal(INCOMECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for INCOME_CODE using the alias name IncomeCode.
     * @param value value to set the INCOME_CODE
     */
    public void setIncomeCode(String value) {
        setAttributeInternal(INCOMECODE, value);
    }

    /**
     * Gets the attribute value for LAST_APPROVED_BY using the alias name LastApprovedBy1.
     * @return the LAST_APPROVED_BY
     */
    public String getLastApprovedBy1() {
        return (String) getAttributeInternal(LASTAPPROVEDBY1);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_APPROVED_BY using the alias name LastApprovedBy1.
     * @param value value to set the LAST_APPROVED_BY
     */
    public void setLastApprovedBy1(String value) {
        setAttributeInternal(LASTAPPROVEDBY1, value);
    }

    /**
     * Gets the attribute value for LAST_APPROVED_DATE using the alias name LastApprovedDate1.
     * @return the LAST_APPROVED_DATE
     */
    public Timestamp getLastApprovedDate1() {
        return (Timestamp) getAttributeInternal(LASTAPPROVEDDATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_APPROVED_DATE using the alias name LastApprovedDate1.
     * @param value value to set the LAST_APPROVED_DATE
     */
    public void setLastApprovedDate1(Timestamp value) {
        setAttributeInternal(LASTAPPROVEDDATE1, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate1.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate1() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate1.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate1(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE1, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy1.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy1() {
        return (String) getAttributeInternal(LASTUPDATEDBY1);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy1.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy1(String value) {
        setAttributeInternal(LASTUPDATEDBY1, value);
    }

    /**
     * Gets the attribute value for LOCAL_TAX_EXEMPT using the alias name LocalTaxExempt.
     * @return the LOCAL_TAX_EXEMPT
     */
    public String getLocalTaxExempt() {
        return (String) getAttributeInternal(LOCALTAXEXEMPT);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCAL_TAX_EXEMPT using the alias name LocalTaxExempt.
     * @param value value to set the LOCAL_TAX_EXEMPT
     */
    public void setLocalTaxExempt(String value) {
        setAttributeInternal(LOCALTAXEXEMPT, value);
    }

    /**
     * Gets the attribute value for MAILING_ADDR_LINE1 using the alias name MailingAddrLine1.
     * @return the MAILING_ADDR_LINE1
     */
    public String getMailingAddrLine1() {
        return (String) getAttributeInternal(MAILINGADDRLINE1);
    }

    /**
     * Sets <code>value</code> as attribute value for MAILING_ADDR_LINE1 using the alias name MailingAddrLine1.
     * @param value value to set the MAILING_ADDR_LINE1
     */
    public void setMailingAddrLine1(String value) {
        setAttributeInternal(MAILINGADDRLINE1, value);
    }

    /**
     * Gets the attribute value for MAILING_ADDR_LINE2 using the alias name MailingAddrLine2.
     * @return the MAILING_ADDR_LINE2
     */
    public String getMailingAddrLine2() {
        return (String) getAttributeInternal(MAILINGADDRLINE2);
    }

    /**
     * Sets <code>value</code> as attribute value for MAILING_ADDR_LINE2 using the alias name MailingAddrLine2.
     * @param value value to set the MAILING_ADDR_LINE2
     */
    public void setMailingAddrLine2(String value) {
        setAttributeInternal(MAILINGADDRLINE2, value);
    }

    /**
     * Gets the attribute value for MAILING_ADDR_LINE3 using the alias name MailingAddrLine3.
     * @return the MAILING_ADDR_LINE3
     */
    public String getMailingAddrLine3() {
        return (String) getAttributeInternal(MAILINGADDRLINE3);
    }

    /**
     * Sets <code>value</code> as attribute value for MAILING_ADDR_LINE3 using the alias name MailingAddrLine3.
     * @param value value to set the MAILING_ADDR_LINE3
     */
    public void setMailingAddrLine3(String value) {
        setAttributeInternal(MAILINGADDRLINE3, value);
    }

    /**
     * Gets the attribute value for MAILING_ADDR_LINE4 using the alias name MailingAddrLine4.
     * @return the MAILING_ADDR_LINE4
     */
    public String getMailingAddrLine4() {
        return (String) getAttributeInternal(MAILINGADDRLINE4);
    }

    /**
     * Sets <code>value</code> as attribute value for MAILING_ADDR_LINE4 using the alias name MailingAddrLine4.
     * @param value value to set the MAILING_ADDR_LINE4
     */
    public void setMailingAddrLine4(String value) {
        setAttributeInternal(MAILINGADDRLINE4, value);
    }

    /**
     * Gets the attribute value for MAILING_CITY using the alias name MailingCity.
     * @return the MAILING_CITY
     */
    public String getMailingCity() {
        return (String) getAttributeInternal(MAILINGCITY);
    }

    /**
     * Sets <code>value</code> as attribute value for MAILING_CITY using the alias name MailingCity.
     * @param value value to set the MAILING_CITY
     */
    public void setMailingCity(String value) {
        setAttributeInternal(MAILINGCITY, value);
    }

    /**
     * Gets the attribute value for MAILING_COUNTRY_CODE using the alias name MailingCountryCode.
     * @return the MAILING_COUNTRY_CODE
     */
    public String getMailingCountryCode() {
        return (String) getAttributeInternal(MAILINGCOUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for MAILING_COUNTRY_CODE using the alias name MailingCountryCode.
     * @param value value to set the MAILING_COUNTRY_CODE
     */
    public void setMailingCountryCode(String value) {
        setAttributeInternal(MAILINGCOUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for MAILING_STATE using the alias name MailingState.
     * @return the MAILING_STATE
     */
    public String getMailingState() {
        return (String) getAttributeInternal(MAILINGSTATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MAILING_STATE using the alias name MailingState.
     * @param value value to set the MAILING_STATE
     */
    public void setMailingState(String value) {
        setAttributeInternal(MAILINGSTATE, value);
    }

    /**
     * Gets the attribute value for MAILING_ZIP_CODE using the alias name MailingZipCode.
     * @return the MAILING_ZIP_CODE
     */
    public String getMailingZipCode() {
        return (String) getAttributeInternal(MAILINGZIPCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for MAILING_ZIP_CODE using the alias name MailingZipCode.
     * @param value value to set the MAILING_ZIP_CODE
     */
    public void setMailingZipCode(String value) {
        setAttributeInternal(MAILINGZIPCODE, value);
    }

    /**
     * Gets the attribute value for MARITAL_STATUS using the alias name MaritalStatus.
     * @return the MARITAL_STATUS
     */
    public String getMaritalStatus() {
        return (String) getAttributeInternal(MARITALSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for MARITAL_STATUS using the alias name MaritalStatus.
     * @param value value to set the MARITAL_STATUS
     */
    public void setMaritalStatus(String value) {
        setAttributeInternal(MARITALSTATUS, value);
    }

    /**
     * Gets the attribute value for MEMBER_ID using the alias name MemberId2.
     * @return the MEMBER_ID
     */
    public String getMemberId2() {
        return (String) getAttributeInternal(MEMBERID2);
    }

    /**
     * Sets <code>value</code> as attribute value for MEMBER_ID using the alias name MemberId2.
     * @param value value to set the MEMBER_ID
     */
    public void setMemberId2(String value) {
        setAttributeInternal(MEMBERID2, value);
    }

    /**
     * Gets the attribute value for MONTHLY_SALARY using the alias name MonthlySalary.
     * @return the MONTHLY_SALARY
     */
    public BigDecimal getMonthlySalary() {
        return (BigDecimal) getAttributeInternal(MONTHLYSALARY);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTHLY_SALARY using the alias name MonthlySalary.
     * @param value value to set the MONTHLY_SALARY
     */
    public void setMonthlySalary(BigDecimal value) {
        setAttributeInternal(MONTHLYSALARY, value);
    }

    /**
     * Gets the attribute value for MOTHER_MAIDEN_NAME using the alias name MotherMaidenName.
     * @return the MOTHER_MAIDEN_NAME
     */
    public String getMotherMaidenName() {
        return (String) getAttributeInternal(MOTHERMAIDENNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for MOTHER_MAIDEN_NAME using the alias name MotherMaidenName.
     * @param value value to set the MOTHER_MAIDEN_NAME
     */
    public void setMotherMaidenName(String value) {
        setAttributeInternal(MOTHERMAIDENNAME, value);
    }

    /**
     * Gets the attribute value for NATIONALITY using the alias name Nationality.
     * @return the NATIONALITY
     */
    public String getNationality() {
        return (String) getAttributeInternal(NATIONALITY);
    }

    /**
     * Sets <code>value</code> as attribute value for NATIONALITY using the alias name Nationality.
     * @param value value to set the NATIONALITY
     */
    public void setNationality(String value) {
        setAttributeInternal(NATIONALITY, value);
    }

    /**
     * Gets the attribute value for NO_OF_DEPENDENTS using the alias name NoOfDependents.
     * @return the NO_OF_DEPENDENTS
     */
    public Integer getNoOfDependents() {
        return (Integer) getAttributeInternal(NOOFDEPENDENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for NO_OF_DEPENDENTS using the alias name NoOfDependents.
     * @param value value to set the NO_OF_DEPENDENTS
     */
    public void setNoOfDependents(Integer value) {
        setAttributeInternal(NOOFDEPENDENTS, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId1.
     * @return the OBJECT_VERSION_ID
     */
    public Long getObjectVersionId1() {
        return (Long) getAttributeInternal(OBJECTVERSIONID1);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId1.
     * @param value value to set the OBJECT_VERSION_ID
     */
    public void setObjectVersionId1(Long value) {
        setAttributeInternal(OBJECTVERSIONID1, value);
    }

    /**
     * Gets the attribute value for OCCUPATION_CODE using the alias name OccupationCode.
     * @return the OCCUPATION_CODE
     */
    public String getOccupationCode() {
        return (String) getAttributeInternal(OCCUPATIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for OCCUPATION_CODE using the alias name OccupationCode.
     * @param value value to set the OCCUPATION_CODE
     */
    public void setOccupationCode(String value) {
        setAttributeInternal(OCCUPATIONCODE, value);
    }

    /**
     * Gets the attribute value for PASSPORT_NO using the alias name PassportNo.
     * @return the PASSPORT_NO
     */
    public String getPassportNo() {
        return (String) getAttributeInternal(PASSPORTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PASSPORT_NO using the alias name PassportNo.
     * @param value value to set the PASSPORT_NO
     */
    public void setPassportNo(String value) {
        setAttributeInternal(PASSPORTNO, value);
    }

    /**
     * Gets the attribute value for PERMANENT_ADDR_LINE1 using the alias name PermanentAddrLine1.
     * @return the PERMANENT_ADDR_LINE1
     */
    public String getPermanentAddrLine1() {
        return (String) getAttributeInternal(PERMANENTADDRLINE1);
    }

    /**
     * Sets <code>value</code> as attribute value for PERMANENT_ADDR_LINE1 using the alias name PermanentAddrLine1.
     * @param value value to set the PERMANENT_ADDR_LINE1
     */
    public void setPermanentAddrLine1(String value) {
        setAttributeInternal(PERMANENTADDRLINE1, value);
    }

    /**
     * Gets the attribute value for PERMANENT_ADDR_LINE2 using the alias name PermanentAddrLine2.
     * @return the PERMANENT_ADDR_LINE2
     */
    public String getPermanentAddrLine2() {
        return (String) getAttributeInternal(PERMANENTADDRLINE2);
    }

    /**
     * Sets <code>value</code> as attribute value for PERMANENT_ADDR_LINE2 using the alias name PermanentAddrLine2.
     * @param value value to set the PERMANENT_ADDR_LINE2
     */
    public void setPermanentAddrLine2(String value) {
        setAttributeInternal(PERMANENTADDRLINE2, value);
    }

    /**
     * Gets the attribute value for PERMANENT_ADDR_LINE3 using the alias name PermanentAddrLine3.
     * @return the PERMANENT_ADDR_LINE3
     */
    public String getPermanentAddrLine3() {
        return (String) getAttributeInternal(PERMANENTADDRLINE3);
    }

    /**
     * Sets <code>value</code> as attribute value for PERMANENT_ADDR_LINE3 using the alias name PermanentAddrLine3.
     * @param value value to set the PERMANENT_ADDR_LINE3
     */
    public void setPermanentAddrLine3(String value) {
        setAttributeInternal(PERMANENTADDRLINE3, value);
    }

    /**
     * Gets the attribute value for PERMANENT_ADDR_LINE4 using the alias name PermanentAddrLine4.
     * @return the PERMANENT_ADDR_LINE4
     */
    public String getPermanentAddrLine4() {
        return (String) getAttributeInternal(PERMANENTADDRLINE4);
    }

    /**
     * Sets <code>value</code> as attribute value for PERMANENT_ADDR_LINE4 using the alias name PermanentAddrLine4.
     * @param value value to set the PERMANENT_ADDR_LINE4
     */
    public void setPermanentAddrLine4(String value) {
        setAttributeInternal(PERMANENTADDRLINE4, value);
    }

    /**
     * Gets the attribute value for PERMANENT_CITY using the alias name PermanentCity.
     * @return the PERMANENT_CITY
     */
    public String getPermanentCity() {
        return (String) getAttributeInternal(PERMANENTCITY);
    }

    /**
     * Sets <code>value</code> as attribute value for PERMANENT_CITY using the alias name PermanentCity.
     * @param value value to set the PERMANENT_CITY
     */
    public void setPermanentCity(String value) {
        setAttributeInternal(PERMANENTCITY, value);
    }

    /**
     * Gets the attribute value for PERMANENT_COUNTRY_CODE using the alias name PermanentCountryCode.
     * @return the PERMANENT_COUNTRY_CODE
     */
    public String getPermanentCountryCode() {
        return (String) getAttributeInternal(PERMANENTCOUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PERMANENT_COUNTRY_CODE using the alias name PermanentCountryCode.
     * @param value value to set the PERMANENT_COUNTRY_CODE
     */
    public void setPermanentCountryCode(String value) {
        setAttributeInternal(PERMANENTCOUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for PERMANENT_COUNTRY_DESC using the alias name PermanentCountryDesc.
     * @return the PERMANENT_COUNTRY_DESC
     */
    public String getPermanentCountryDesc() {
        return (String) getAttributeInternal(PERMANENTCOUNTRYDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for PERMANENT_COUNTRY_DESC using the alias name PermanentCountryDesc.
     * @param value value to set the PERMANENT_COUNTRY_DESC
     */
    public void setPermanentCountryDesc(String value) {
        setAttributeInternal(PERMANENTCOUNTRYDESC, value);
    }

    /**
     * Gets the attribute value for PERMANENT_STATE using the alias name PermanentState.
     * @return the PERMANENT_STATE
     */
    public String getPermanentState() {
        return (String) getAttributeInternal(PERMANENTSTATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PERMANENT_STATE using the alias name PermanentState.
     * @param value value to set the PERMANENT_STATE
     */
    public void setPermanentState(String value) {
        setAttributeInternal(PERMANENTSTATE, value);
    }

    /**
     * Gets the attribute value for PERMANENT_ZIP_CODE using the alias name PermanentZipCode.
     * @return the PERMANENT_ZIP_CODE
     */
    public String getPermanentZipCode() {
        return (String) getAttributeInternal(PERMANENTZIPCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PERMANENT_ZIP_CODE using the alias name PermanentZipCode.
     * @param value value to set the PERMANENT_ZIP_CODE
     */
    public void setPermanentZipCode(String value) {
        setAttributeInternal(PERMANENTZIPCODE, value);
    }

    /**
     * Gets the attribute value for POWER_OF_ATTORNEY using the alias name PowerOfAttorney.
     * @return the POWER_OF_ATTORNEY
     */
    public String getPowerOfAttorney() {
        return (String) getAttributeInternal(POWEROFATTORNEY);
    }

    /**
     * Sets <code>value</code> as attribute value for POWER_OF_ATTORNEY using the alias name PowerOfAttorney.
     * @param value value to set the POWER_OF_ATTORNEY
     */
    public void setPowerOfAttorney(String value) {
        setAttributeInternal(POWEROFATTORNEY, value);
    }

    /**
     * Gets the attribute value for PP_EXPIRY_DATE using the alias name PpExpiryDate.
     * @return the PP_EXPIRY_DATE
     */
    public Timestamp getPpExpiryDate() {
        return (Timestamp) getAttributeInternal(PPEXPIRYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PP_EXPIRY_DATE using the alias name PpExpiryDate.
     * @param value value to set the PP_EXPIRY_DATE
     */
    public void setPpExpiryDate(Timestamp value) {
        setAttributeInternal(PPEXPIRYDATE, value);
    }

    /**
     * Gets the attribute value for PP_ISSUE_DATE using the alias name PpIssueDate.
     * @return the PP_ISSUE_DATE
     */
    public Timestamp getPpIssueDate() {
        return (Timestamp) getAttributeInternal(PPISSUEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PP_ISSUE_DATE using the alias name PpIssueDate.
     * @param value value to set the PP_ISSUE_DATE
     */
    public void setPpIssueDate(Timestamp value) {
        setAttributeInternal(PPISSUEDATE, value);
    }

    /**
     * Gets the attribute value for RESIDENCE_TIN1 using the alias name ResidenceTin1.
     * @return the RESIDENCE_TIN1
     */
    public String getResidenceTin1() {
        return (String) getAttributeInternal(RESIDENCETIN1);
    }

    /**
     * Sets <code>value</code> as attribute value for RESIDENCE_TIN1 using the alias name ResidenceTin1.
     * @param value value to set the RESIDENCE_TIN1
     */
    public void setResidenceTin1(String value) {
        setAttributeInternal(RESIDENCETIN1, value);
    }

    /**
     * Gets the attribute value for RESIDENCE_TIN2 using the alias name ResidenceTin2.
     * @return the RESIDENCE_TIN2
     */
    public String getResidenceTin2() {
        return (String) getAttributeInternal(RESIDENCETIN2);
    }

    /**
     * Sets <code>value</code> as attribute value for RESIDENCE_TIN2 using the alias name ResidenceTin2.
     * @param value value to set the RESIDENCE_TIN2
     */
    public void setResidenceTin2(String value) {
        setAttributeInternal(RESIDENCETIN2, value);
    }

    /**
     * Gets the attribute value for RESIDENCE_TIN3 using the alias name ResidenceTin3.
     * @return the RESIDENCE_TIN3
     */
    public String getResidenceTin3() {
        return (String) getAttributeInternal(RESIDENCETIN3);
    }

    /**
     * Sets <code>value</code> as attribute value for RESIDENCE_TIN3 using the alias name ResidenceTin3.
     * @param value value to set the RESIDENCE_TIN3
     */
    public void setResidenceTin3(String value) {
        setAttributeInternal(RESIDENCETIN3, value);
    }

    /**
     * Gets the attribute value for RESIDENCE_TIN4 using the alias name ResidenceTin4.
     * @return the RESIDENCE_TIN4
     */
    public String getResidenceTin4() {
        return (String) getAttributeInternal(RESIDENCETIN4);
    }

    /**
     * Sets <code>value</code> as attribute value for RESIDENCE_TIN4 using the alias name ResidenceTin4.
     * @param value value to set the RESIDENCE_TIN4
     */
    public void setResidenceTin4(String value) {
        setAttributeInternal(RESIDENCETIN4, value);
    }

    /**
     * Gets the attribute value for RESIDENCY_CODE using the alias name ResidencyCode.
     * @return the RESIDENCY_CODE
     */
    public Integer getResidencyCode() {
        return (Integer) getAttributeInternal(RESIDENCYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for RESIDENCY_CODE using the alias name ResidencyCode.
     * @param value value to set the RESIDENCY_CODE
     */
    public void setResidencyCode(Integer value) {
        setAttributeInternal(RESIDENCYCODE, value);
    }

    /**
     * Gets the attribute value for SHAREHOLDER_CODE using the alias name ShareholderCode.
     * @return the SHAREHOLDER_CODE
     */
    public String getShareholderCode() {
        return (String) getAttributeInternal(SHAREHOLDERCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SHAREHOLDER_CODE using the alias name ShareholderCode.
     * @param value value to set the SHAREHOLDER_CODE
     */
    public void setShareholderCode(String value) {
        setAttributeInternal(SHAREHOLDERCODE, value);
    }

    /**
     * Gets the attribute value for STREET_TYPE using the alias name StreetType.
     * @return the STREET_TYPE
     */
    public String getStreetType() {
        return (String) getAttributeInternal(STREETTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for STREET_TYPE using the alias name StreetType.
     * @param value value to set the STREET_TYPE
     */
    public void setStreetType(String value) {
        setAttributeInternal(STREETTYPE, value);
    }

    /**
     * Gets the attribute value for WORK_PHONE using the alias name WorkPhone.
     * @return the WORK_PHONE
     */
    public String getWorkPhone() {
        return (String) getAttributeInternal(WORKPHONE);
    }

    /**
     * Sets <code>value</code> as attribute value for WORK_PHONE using the alias name WorkPhone.
     * @param value value to set the WORK_PHONE
     */
    public void setWorkPhone(String value) {
        setAttributeInternal(WORKPHONE, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CardTypeVA.
     */
    public RowSet getCardTypeVA() {
        return (RowSet) getAttributeInternal(CARDTYPEVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LincuUnionsVA.
     */
    public RowSet getLincuUnionsVA() {
        return (RowSet) getAttributeInternal(LINCUUNIONSVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MemberVA.
     */
    public RowSet getMemberVA() {
        return (RowSet) getAttributeInternal(MEMBERVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ApplicationStatusVA.
     */
    public RowSet getApplicationStatusVA() {
        return (RowSet) getAttributeInternal(APPLICATIONSTATUSVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryVA.
     */
    public RowSet getCountryVA() {
        return (RowSet) getAttributeInternal(COUNTRYVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GenderVA.
     */
    public RowSet getGenderVA() {
        return (RowSet) getAttributeInternal(GENDERVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MaritalStatusVA.
     */
    public RowSet getMaritalStatusVA() {
        return (RowSet) getAttributeInternal(MARITALSTATUSVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> YesOrNoVA.
     */
    public RowSet getYesOrNoVA() {
        return (RowSet) getAttributeInternal(YESORNOVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> HomeOwnershipVA.
     */
    public RowSet getHomeOwnershipVA() {
        return (RowSet) getAttributeInternal(HOMEOWNERSHIPVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FCBShareholdingVA.
     */
    public RowSet getFCBShareholdingVA() {
        return (RowSet) getAttributeInternal(FCBSHAREHOLDINGVA);
    }
}

