package com.linCu.model.view;

import com.linCu.model.view.common.LincuUserInfoVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 05 17:38:34 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LincuUserInfoVOImpl extends ViewObjectImpl implements LincuUserInfoVO {
    /**
     * This is the default constructor (do not remove).
     */
    public LincuUserInfoVOImpl() {
    }
    
    public String loginUser(){
        return null;
    }
    
    public String resetPassword(String oldPassword, String newPassword, String confirmPassword, String securityAns){
        if((newPassword != null) && (confirmPassword != null) && newPassword.equalsIgnoreCase(confirmPassword)){
            
           LincuUserInfoVORowImpl row = (LincuUserInfoVORowImpl) this.getCurrentRow();
           if(row != null){
              String password =  row.getPassword();
              if((oldPassword != null) && (password != null) && oldPassword.equalsIgnoreCase(password)){
                  row.setPassword(newPassword);
                  row.setSecurityQustnAns(securityAns);
                  row.setFirstLoginFlag("N");
                  this.getDBTransaction().commit();
                  return "success";
              }else{
                  return "InvalidOldPassword";
              }
           }
            
        }else{
            return "MismatchInConfirmPassword";
        }
        
        this.getCurrentRow();
        
        return "failure";
    }
    
}

