package com.linCu.model.view;

import com.linCu.model.view.common.LincuMemberCardDocsVO;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 10 07:50:23 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LincuMemberCardDocsVOImpl extends ViewObjectImpl implements LincuMemberCardDocsVO {
    /**
     * This is the default constructor (do not remove).
     */
    public LincuMemberCardDocsVOImpl() {
    }
    
    public void removeCurrentRow(){
        Row row = this.getCurrentRow();
        if(row != null){
            row.remove();
        }
    }
}

