package com.linCu.model.view;

import com.linCu.model.view.common.LincuMemberCardVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 03 10:26:00 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LincuMemberCardVOImpl extends ViewObjectImpl implements LincuMemberCardVO {
    /**
     * This is the default constructor (do not remove).
     */
    public LincuMemberCardVOImpl() {
    }
    
    
    public void submitCard(){
        LincuMemberCardVORowImpl row = (LincuMemberCardVORowImpl)this.getCurrentRow();
        if(row != null){
            long time = System.currentTimeMillis();
            java.sql.Timestamp timestamp = new java.sql.Timestamp(time);
            row.setSubmittedOn(timestamp);
            row.setCardStatus("SUBMITTED");
        }
        
    }
    
    public void approve(String approver){
        LincuMemberCardVORowImpl row = (LincuMemberCardVORowImpl)this.getCurrentRow();
        if(row != null){
            long time = System.currentTimeMillis();
            java.sql.Timestamp timestamp = new java.sql.Timestamp(time);
            row.setAuthorizedOn(timestamp);
            row.setAuthorizedBy(approver);
            row.setCardStatus("AUTHORIZED");
        }
        
    }
    
    public void reject(String rejector){
        LincuMemberCardVORowImpl row = (LincuMemberCardVORowImpl)this.getCurrentRow();
        if(row != null){
            long time = System.currentTimeMillis();
            java.sql.Timestamp timestamp = new java.sql.Timestamp(time);
            row.setAuthorizedOn(timestamp);
            row.setAuthorizedBy(rejector);
            row.setCardStatus("REJECTED");
        }
        
    }
    
    public void lincuApprove(String approver){
        LincuMemberCardVORowImpl row = (LincuMemberCardVORowImpl)this.getCurrentRow();
        if(row != null){
            long time = System.currentTimeMillis();
            java.sql.Timestamp timestamp = new java.sql.Timestamp(time);
            row.setAuthorizedOn(timestamp);
            row.setAuthorizedBy(approver);
            row.setCardStatus("LINCU_AUTHORIZED");
        }
        
    }
    
    public void lincuReject(String rejector){
        LincuMemberCardVORowImpl row = (LincuMemberCardVORowImpl)this.getCurrentRow();
        if(row != null){
            long time = System.currentTimeMillis();
            java.sql.Timestamp timestamp = new java.sql.Timestamp(time);
            row.setAuthorizedOn(timestamp);
            row.setAuthorizedBy(rejector);
            row.setCardStatus("LINCU_REJECTED");
        }
        
    }
    
    public void fcbApprove(String approver){
        LincuMemberCardVORowImpl row = (LincuMemberCardVORowImpl)this.getCurrentRow();
        if(row != null){
            long time = System.currentTimeMillis();
            java.sql.Timestamp timestamp = new java.sql.Timestamp(time);
            row.setAuthorizedOn(timestamp);
            row.setAuthorizedBy(approver);
            row.setCardStatus("FCB_AUTHORIZED");
        }
        
    }
    
    public void fcbReject(String rejector){
        LincuMemberCardVORowImpl row = (LincuMemberCardVORowImpl)this.getCurrentRow();
        if(row != null){
            long time = System.currentTimeMillis();
            java.sql.Timestamp timestamp = new java.sql.Timestamp(time);
            row.setAuthorizedOn(timestamp);
            row.setAuthorizedBy(rejector);
            row.setCardStatus("FCB_REJECTED");
        }
        
    }
    public void requestCard(String requestor, String creditUnionId){
        LincuMemberCardVORowImpl row = (LincuMemberCardVORowImpl) this.createRow();
        if(row != null){
        this.insertRow(row);
        this.setCurrentRow(row);
        row.setCreditUnionId(creditUnionId);
        row.setCreatedBy(requestor);
        long time = System.currentTimeMillis();
        java.sql.Timestamp timestamp = new java.sql.Timestamp(time);
        row.setCreatedOn(timestamp);
        }
    }

    /**
     * Returns the variable value for bindStatus.
     * @return variable value for bindStatus
     */
    public String getbindStatus() {
        return (String) ensureVariableManager().getVariableValue("bindStatus");
    }

    /**
     * Sets <code>value</code> for variable bindStatus.
     * @param value value to bind as bindStatus
     */
    public void setbindStatus(String value) {
        ensureVariableManager().setVariableValue("bindStatus", value);
    }

    /**
     * Returns the variable value for bindStatus1.
     * @return variable value for bindStatus1
     */
    public String getbindStatus1() {
        return (String) ensureVariableManager().getVariableValue("bindStatus1");
    }

    /**
     * Sets <code>value</code> for variable bindStatus1.
     * @param value value to bind as bindStatus1
     */
    public void setbindStatus1(String value) {
        ensureVariableManager().setVariableValue("bindStatus1", value);
    }

    /**
     * Returns the variable value for bindStatus2.
     * @return variable value for bindStatus2
     */
    public String getbindStatus2() {
        return (String) ensureVariableManager().getVariableValue("bindStatus2");
    }

    /**
     * Sets <code>value</code> for variable bindStatus2.
     * @param value value to bind as bindStatus2
     */
    public void setbindStatus2(String value) {
        ensureVariableManager().setVariableValue("bindStatus2", value);
    }

    /**
     * Returns the variable value for bindStatus3.
     * @return variable value for bindStatus3
     */
    public String getbindStatus3() {
        return (String) ensureVariableManager().getVariableValue("bindStatus3");
    }

    /**
     * Sets <code>value</code> for variable bindStatus3.
     * @param value value to bind as bindStatus3
     */
    public void setbindStatus3(String value) {
        ensureVariableManager().setVariableValue("bindStatus3", value);
    }

    /**
     * Returns the variable value for bindStatus4.
     * @return variable value for bindStatus4
     */
    public String getbindStatus4() {
        return (String) ensureVariableManager().getVariableValue("bindStatus4");
    }

    /**
     * Sets <code>value</code> for variable bindStatus4.
     * @param value value to bind as bindStatus4
     */
    public void setbindStatus4(String value) {
        ensureVariableManager().setVariableValue("bindStatus4", value);
    }

    /**
     * Returns the variable value for bindCreditUnionId.
     * @return variable value for bindCreditUnionId
     */
    public String getbindCreditUnionId() {
        return (String) ensureVariableManager().getVariableValue("bindCreditUnionId");
    }

    /**
     * Sets <code>value</code> for variable bindCreditUnionId.
     * @param value value to bind as bindCreditUnionId
     */
    public void setbindCreditUnionId(String value) {
        ensureVariableManager().setVariableValue("bindCreditUnionId", value);
    }

    /**
     * Returns the variable value for bindStatus5.
     * @return variable value for bindStatus5
     */
    public String getbindStatus5() {
        return (String) ensureVariableManager().getVariableValue("bindStatus5");
    }

    /**
     * Sets <code>value</code> for variable bindStatus5.
     * @param value value to bind as bindStatus5
     */
    public void setbindStatus5(String value) {
        ensureVariableManager().setVariableValue("bindStatus5", value);
    }
}

