package com.linCu.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 20 22:39:40 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LincuMemberCardAuditVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LincuMemberCardAuditVOImpl() {
    }
}

