package com.linCu.model.view;

import java.math.BigDecimal;

import oracle.jbo.RowSet;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 10 07:50:20 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LincuMemberCardDocsVORowImpl extends ViewRowImpl {


    public static final int ENTITY_LINCUMEMBERCARDDOCSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CardId,
        DocDesc,
        DocId,
        Document,
        DocumentName,
        DocumentType,
        Required,
        DocumentType1,
        Path,
        DocumentTypeVA,
        AddExtraDocsVA;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CARDID = AttributesEnum.CardId.index();
    public static final int DOCDESC = AttributesEnum.DocDesc.index();
    public static final int DOCID = AttributesEnum.DocId.index();
    public static final int DOCUMENT = AttributesEnum.Document.index();
    public static final int DOCUMENTNAME = AttributesEnum.DocumentName.index();
    public static final int DOCUMENTTYPE = AttributesEnum.DocumentType.index();
    public static final int REQUIRED = AttributesEnum.Required.index();
    public static final int DOCUMENTTYPE1 = AttributesEnum.DocumentType1.index();
    public static final int PATH = AttributesEnum.Path.index();
    public static final int DOCUMENTTYPEVA = AttributesEnum.DocumentTypeVA.index();
    public static final int ADDEXTRADOCSVA = AttributesEnum.AddExtraDocsVA.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LincuMemberCardDocsVORowImpl() {
    }

    /**
     * Gets LincuMemberCardDocsEO entity object.
     * @return the LincuMemberCardDocsEO
     */
    public EntityImpl getLincuMemberCardDocsEO() {
        return (EntityImpl) getEntity(ENTITY_LINCUMEMBERCARDDOCSEO);
    }

    /**
     * Gets the attribute value for CARD_ID using the alias name CardId.
     * @return the CARD_ID
     */
    public BigDecimal getCardId() {
        return (BigDecimal) getAttributeInternal(CARDID);
    }

    /**
     * Sets <code>value</code> as attribute value for CARD_ID using the alias name CardId.
     * @param value value to set the CARD_ID
     */
    public void setCardId(BigDecimal value) {
        setAttributeInternal(CARDID, value);
    }

    /**
     * Gets the attribute value for DOC_DESC using the alias name DocDesc.
     * @return the DOC_DESC
     */
    public String getDocDesc() {
        return (String) getAttributeInternal(DOCDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_DESC using the alias name DocDesc.
     * @param value value to set the DOC_DESC
     */
    public void setDocDesc(String value) {
        setAttributeInternal(DOCDESC, value);
    }

    /**
     * Gets the attribute value for DOC_ID using the alias name DocId.
     * @return the DOC_ID
     */
    public BigDecimal getDocId() {
        return (BigDecimal) getAttributeInternal(DOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_ID using the alias name DocId.
     * @param value value to set the DOC_ID
     */
    public void setDocId(BigDecimal value) {
        setAttributeInternal(DOCID, value);
    }

    /**
     * Gets the attribute value for DOCUMENT using the alias name Document.
     * @return the DOCUMENT
     */
    public BlobDomain getDocument() {
        return (BlobDomain) getAttributeInternal(DOCUMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCUMENT using the alias name Document.
     * @param value value to set the DOCUMENT
     */
    public void setDocument(BlobDomain value) {
        setAttributeInternal(DOCUMENT, value);
    }

    /**
     * Gets the attribute value for DOCUMENT_NAME using the alias name DocumentName.
     * @return the DOCUMENT_NAME
     */
    public String getDocumentName() {
        return (String) getAttributeInternal(DOCUMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCUMENT_NAME using the alias name DocumentName.
     * @param value value to set the DOCUMENT_NAME
     */
    public void setDocumentName(String value) {
        setAttributeInternal(DOCUMENTNAME, value);
    }

    /**
     * Gets the attribute value for DOCUMENT_TYPE using the alias name DocumentType.
     * @return the DOCUMENT_TYPE
     */
    public String getDocumentType() {
        return (String) getAttributeInternal(DOCUMENTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCUMENT_TYPE using the alias name DocumentType.
     * @param value value to set the DOCUMENT_TYPE
     */
    public void setDocumentType(String value) {
        setAttributeInternal(DOCUMENTTYPE, value);
    }

    /**
     * Gets the attribute value for REQUIRED using the alias name Required.
     * @return the REQUIRED
     */
    public String getRequired() {
        return (String) getAttributeInternal(REQUIRED);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUIRED using the alias name Required.
     * @param value value to set the REQUIRED
     */
    public void setRequired(String value) {
        setAttributeInternal(REQUIRED, value);
    }

    /**
     * Gets the attribute value for DOCUMENT_TYPE using the alias name DocumentType1.
     * @return the DOCUMENT_TYPE
     */
    public String getDocumentType1() {
        return (String) getAttributeInternal(DOCUMENTTYPE1);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCUMENT_TYPE using the alias name DocumentType1.
     * @param value value to set the DOCUMENT_TYPE
     */
    public void setDocumentType1(String value) {
        setAttributeInternal(DOCUMENTTYPE1, value);
    }

    /**
     * Gets the attribute value for PATH using the alias name Path.
     * @return the PATH
     */
    public String getPath() {
        return (String) getAttributeInternal(PATH);
    }

    /**
     * Sets <code>value</code> as attribute value for PATH using the alias name Path.
     * @param value value to set the PATH
     */
    public void setPath(String value) {
        setAttributeInternal(PATH, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DocumentTypeVA.
     */
    public RowSet getDocumentTypeVA() {
        return (RowSet) getAttributeInternal(DOCUMENTTYPEVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AddExtraDocsVA.
     */
    public RowSet getAddExtraDocsVA() {
        return (RowSet) getAttributeInternal(ADDEXTRADOCSVA);
    }
}

